// IntroVoiceover — plays the welcome narration during the intro stinger
// so the opener isn't silent. Driven by lesson.introVoiceover.audioFile
// (generated by scripts/generate-intros.mjs). No-op if unset.
//
// Volume slightly under full (0.9) so the music bed stays audible
// underneath, then the music itself fades to silence by the time the
// title scene begins.

import {Audio, staticFile} from 'remotion';

type IntroVoiceoverProps = {
	src?: string;
};

const toStaticPath = (p: string) => p.replace(/^public[\\/]/, '').replace(/\\/g, '/');

export const IntroVoiceover = ({src}: IntroVoiceoverProps) => {
	if (!src) return null;
	return <Audio src={staticFile(toStaticPath(src))} volume={0.95} />;
};
