import assert from 'node:assert/strict';
import {hash,stringFields} from './science-audit.mjs';
import {removeMediaAndCues} from './science-corrections.mjs';
import {removeSpeechCues} from './quantitative-lessons.mjs';
import {getVoiceoverBudget} from '../lesson-utils.mjs';
import {validateReviewedMedicineDiagram} from '../../src/slides/diagrams/medicine-models.mjs';
export const medicineSources={
 'chemistry-y12-m8-l11-drug-classification-functional-groups':'79bea4a37ac1beaeda455923fd5c7a64f1b2f0240331271f54e6c10e2649d3b8',
 'chemistry-y12-m8-l12-acid-base-properties-drug-molecules':'40ae029fbdabcb51281d2d9c1253b14fb884386d4febe659a7e8a52820bde900',
};
export const medicineEvidence=[
 {url:'https://goldbook.iupac.org/terms/view/11485',scope:'A pharmacophore describes an ensemble of target-relevant features, not one functional group.'},
 {url:'https://old.iupac.org/publications/pac/1998/pdf/7005x1129.pdf',scope:'Original IUPAC recommendations explicitly reject naming simple functionalities pharmacophores.'},
 {url:'https://pubmed.ncbi.nlm.nih.gov/810797/',scope:'Original enzyme experiments support aspirin acting as an active-site acetylating agent. They do not prove equal efficacy or clinical safety from a retained COOH group.'},
 {url:'https://pubmed.ncbi.nlm.nih.gov/3733281/',scope:'Small original crossover study: formulation affected aspirin absorption kinetics. It is evidence against predicting kinetics from pKa alone, not a universal numerical absorption estimate.'},
 {url:'https://pubmed.ncbi.nlm.nih.gov/11228592/',scope:'Original observational study found similar upper gastrointestinal complication risks for plain and coated formulations. Coating is not proof of clinical protection.'},
 {url:'https://pubmed.ncbi.nlm.nih.gov/1888645/',scope:'Short-term endoscopic study found less local damage with coating. Its endpoint differs from serious clinical bleeding; do not generalise either endpoint.'},
 {url:'https://www.nsw.gov.au/sites/default/files/noindex/2025-03/chemistry-stage6-syllabus-word.docx',scope:'Official 2017 syllabus: retain drug examples as enrichment, not a claimed mandatory Module 8 medicine-action or delivery requirement. Mapping and teaching review remain pending.'},
];
const bullets=values=>values.map(text=>({text}));
export function assertUnvoicedMedicineDraft(draft){
 const walk=(value,trail='')=>{if(!value||typeof value!=='object')return;for(const [key,child] of Object.entries(value)){
  if(/audio|alignment|backgroundMusic/iu.test(key)||['captions','introVoiceover','responseHold','startFrame','endFrame','delay','beat','beats','at','revealDelays'].includes(key)||/(?:At|Beat)$/u.test(key))throw new Error('Inherited medicine media/cue: '+trail+'.'+key);
  walk(child,trail+'.'+key);
 }};walk(draft);
 if(JSON.stringify(draft).includes('\u2014'))throw new Error('Prohibited punctuation');
 for(const scene of draft.scenes)validateReviewedMedicineDiagram(scene.diagram);
}
export function medicineDraft(name,bytes){
 if(!Object.hasOwn(medicineSources,name)||hash(bytes)!==medicineSources[name])throw new Error('Medicine source changed: review content, not just its hash');
 const original=JSON.parse(bytes),draft=removeSpeechCues(removeMediaAndCues(structuredClone(original)));
 for(const k of ['introVoiceover','productionRole','productionNotes','syllabusDotPoints','nesaOutcomes'])delete draft[k];
 draft.syllabusNeutral=true;
 draft.examSkill='Apply chemical reasoning to an enrichment example under stated assumptions. No specific HSC marking claim or practical outcome is certified.';
 draft.inquiryQuestion='What can chemical structure and equilibrium explain, and what requires separate experimental evidence?';
 const set=(id,copy,text)=>{const s=draft.scenes.find(s=>s.id===id);if(!s)throw new Error('Missing medicine scene '+id);Object.assign(s,copy,{voiceover:{text}});return s;};
 let response;
 if(name.includes('l11-')){
  draft.subtitle='Enrichment: chemical structure, evidence and its limits';
  draft.lessonIntent='Identify functional groups, distinguish classifications, and explain why structure alone cannot establish pharmacological efficacy or clinical safety.';
  draft.scenes[0].caption='Drug structures and functional groups: chemistry enrichment';
  set('hook',{heading:'A small change raises new questions',body:'Acetylating the phenolic OH of salicylic acid gives aspirin. The carboxylic acid remains, but this does not prove unchanged action or improved safety.',callout:'Structure suggests questions; experiments establish effects.',caption:'A structural transformation is not a clinical guarantee.'},'Salicylic acid and aspirin are closely related, but a small structural change can alter more than one property. In aspirin the phenolic O H has been converted to an acetyl ester, while the carboxylic acid remains. That observation does not establish equal effectiveness or less harm. We will identify functional groups and separate chemical predictions from claims that need pharmacological and clinical evidence. These examples extend chemistry concepts; they are not medicine advice.');
  set('concept-classify',{heading:'Function and structure are different classifications',body:'A therapeutic class describes a use. A structural description identifies molecular features.',bullets:bullets(['Analgesics are used to relieve pain.','Aspirin, paracetamol and ibuprofen have different structures.','Sharing a use does not imply an identical mechanism or suitable substitution.']),secondary:'The displayed classes are examples, not an exhaustive or mutually exclusive list.',callout:'Name the basis of classification.',caption:'Similar use does not establish identical chemical behaviour.'},'We can classify a medicine by its use, or describe it by its structure. Analgesic is a use-based category. Aspirin, paracetamol and ibuprofen are all used for pain relief, but their molecular structures differ. Their mechanisms and risks are not identical. The gallery shows example categories, which need not be exhaustive or mutually exclusive. A chemical comparison is not a recommendation to substitute one medicine for another.');
  const groups=set('concept-groups',{heading:'Functional groups guide chemical reasoning',body:'Identify the complete functional group before predicting a possible interaction or reaction.',bullets:bullets(['Carboxylic acids can lose H⁺; amines can accept H⁺ under suitable conditions.','Esters and amides are different groups with different reactivities.','Whole-molecule structure, pH and solid-state properties affect behaviour.']),secondary:'Polarity and hydrogen bonding alone do not determine measured solubility, binding or effectiveness.',callout:'A functional group supports a qualified prediction.',caption:'Conditions and the rest of the molecule matter.'},'A carboxylic acid can donate a proton, while an amine can accept one under suitable conditions. Hydroxyl, ester and amide groups can participate in polar interactions, but their structures and reactivities differ. An amide is not simply an amine beside an unrelated carbonyl. Hydrogen bonding and polarity are useful clues, not a complete prediction of solubility or binding. Consider the whole molecule, its ionisation state, the solvent and its solid form.');
  groups.diagram.rows=[['Hydroxyl or phenol','Hydrogen-bonding possibilities; context matters'],['Carboxylic acid','Can donate H⁺; extent depends on pH and pKa'],['Amine','Can accept H⁺; basicity depends on structure'],['Ester','Polar; hydrolysis depends on conditions'],['Amide','Polar; different basicity and reactivity from an amine'],['Hydrocarbon region','Non-polar contribution; not a solubility verdict']];
  set('concept-reading',{heading:'Read each complete structure',body:'Locate the groups in the displayed aspirin, paracetamol and ibuprofen structures.',bullets:bullets(['Aspirin: carboxylic acid, ester and aromatic ring.','Paracetamol: phenol, amide and aromatic ring.','Ibuprofen: carboxylic acid, aromatic ring and hydrocarbon regions.']),secondary:'These structures identify groups; they do not rank clinical safety or effectiveness.',callout:'Read connectivity, not isolated letters.',caption:'An OH bonded directly to an aromatic ring is phenolic.'},'Read the bonds as well as the atom labels. Aspirin contains a carboxylic acid and an ester attached to an aromatic framework. Paracetamol contains a phenol and an amide. Its nitrogen belongs to that amide, so do not label it as an ordinary amine. Ibuprofen contains a carboxylic acid and substantial hydrocarbon regions. These descriptions support chemical reasoning, but they do not by themselves rank clinical effectiveness or safety.');
  set('definition',{heading:'A pharmacophore is a feature model',bullets:bullets(['An ensemble of spatial and electronic features relevant to a particular biological target.','May describe hydrogen-bonding, charge or hydrophobic features and their arrangement.','It is not automatically one named functional group or a fixed fragment.','A proposed model requires evidence and has a stated target and scope.']),callout:'Do not equate COOH with a complete pharmacophore.',caption:'IUPAC terminology: target-relevant features and their arrangement.'},'A pharmacophore is a model of a combination of spatial and electronic features relevant to interaction with a particular biological target. It can include hydrogen-bonding, charge and hydrophobic features and their arrangement. It is not automatically a single named functional group. Keeping one group does not prove that activity is preserved. A proposed feature model needs evidence and must state the target and response it concerns.');
  const modify=set('concept-pharmacophore',{heading:'Retained group does not mean retained mechanism',body:'Aspirin retains the carboxylic acid and gains an acetyl ester. Its acetylating action matters to its enzyme effects.',bullets:bullets(['The retained COOH contributes to acid-base behaviour.','Original enzyme experiments support an active-site acetylating action.','A structural comparison alone cannot establish equal pain relief or improved clinical safety.']),secondary:'Clinical safety depends on outcomes and evidence, not an “irritating group” label.',callout:'Follow the changed chemistry, then examine evidence.',caption:'The highlighted retained group is not a complete pharmacophore.'},'The carboxylic acid remains when salicylic acid is acetylated, but calling it the complete pharmacophore is misleading. Aspirin can act as an acetylating agent. Original enzyme experiments linked acetylation with inhibition of cyclo-oxygenase activity. This is evidence about a mechanism, not proof that any molecule retaining a carboxylic acid will work equally well. Nor does changing the phenolic group establish improved clinical safety. Separate structural description, mechanism and clinical outcomes.');
  modify.diagram.props={mode:'modify',reviewedMedicine:true};
  set('worked-example',{heading:'What can these clues establish?',question:'An unspecified compound contains an aromatic ring, a carboxylic acid and a branched hydrocarbon region. Can these clues uniquely identify ibuprofen?',coachNote:'Distinguish a compatible candidate from a unique identification.',steps:['The stated groups are compatible with ibuprofen.','Many different connectivities can share these broad features.','The clues do not uniquely identify a molecule.','A complete structure or additional analytical evidence is needed.','Clinical action cannot be inferred from this group list alone.'],caption:'Compatible features do not prove identity.'},'The group list is compatible with ibuprofen, but compatibility is not unique identification. Many compounds can contain an aromatic ring, a carboxylic acid and a branched hydrocarbon region. We need the complete connectivity or additional analytical evidence to identify an unknown. Naming a possible candidate is different from establishing identity. Even a correct group assignment would not alone prove a clinical effect. State the limit of the evidence.');
  set('misconception',{heading:'Avoid one-group explanations',body:'Same use does not mean same structure, and one retained group does not prove the same action.',secondary:'Changing a group can affect ionisation, interactions, reaction pathways and other properties. Evaluate the whole molecule and relevant evidence.',mistakeTag:'Structure is evidence, not a clinical guarantee',callout:'Do not invent a guaranteed mark or universal drug rule.',caption:'Use qualified chemical reasoning.'},'Avoid a one-group explanation of a medicine. The same therapeutic use does not imply the same structure. Retaining a carboxylic acid does not guarantee identical action. Changing a group may influence several chemical and biological properties at once. Explain the specific feature and the evidence that supports your conclusion. Do not turn a useful structural clue into a guaranteed clinical claim or an invented examination marking rule.');
  response={minimumThinkingSeconds:35,promptText:'An ester is added to a molecule while its carboxylic acid remains. A student claims that pain relief must stay the same and the product must be safer. Which parts of that conclusion are established by the structural description? What additional evidence would be needed? Pause and decide.',answerText:'The description establishes a retained carboxylic acid and an added ester, assuming the structure is correct. It does not establish equal pain relief or improved safety. Those conclusions need relevant pharmacological and clinical evidence. Chemical reasoning can propose changed properties, but it must not replace measurements of the claimed outcome.'};
  set('quick-check',{heading:'Separate observation from inference',question:'An ester is added while COOH remains. Does that establish equal pain relief and improved safety? State what is known and what evidence is missing.',pausePrompt:'Pause: identify the structural observation and the unsupported claims.',answerSteps:['Known: the stated functional-group change.','Not established: equal pain relief or improved clinical safety.','Needed: relevant mechanism, pharmacological and clinical evidence.'],caption:'Structure alone does not establish either clinical claim.'},response.promptText+' '+response.answerText);
  set('summary',{heading:'Structure, classification and evidence',points:['Classify by function or structure, stating which.','Identify complete functional groups from connectivity.','A pharmacophore is a target-relevant feature model.','One retained group does not guarantee retained effect.','Distinguish chemical predictions from clinical outcomes.'],finalPrompt:'What does the structure show, and what still needs evidence?',caption:'Chemistry enrichment, not clinical advice or a certified syllabus requirement.'},'Distinguish use-based classifications from structural descriptions. Identify complete functional groups and use them to make qualified chemical predictions. A pharmacophore models a combination of target-relevant features, not automatically one functional group. Keeping a group does not guarantee the same action or improved safety. Finish by stating what the structure establishes and what still needs experimental or clinical evidence.');
 }else{
  draft.subtitle='Enrichment: equilibrium fractions are not absorption predictions';
  draft.lessonIntent='Calculate ideal weak-acid ionisation ratios and fractions, separating equilibrium chemistry from measured solubility, absorption and bioavailability.';
  draft.scenes[0].caption='Weak-acid ionisation and medicine examples: chemistry enrichment';
  set('hook',{heading:'pH does not decide absorption by itself',body:'An enteric coating can change where and when a formulation releases a drug. Its behaviour is not determined by the drug pKa alone.',callout:'Release, ionisation and absorption are different questions.',caption:'A coating is not proof of protection from serious gastrointestinal harm.'},'Why might a coated tablet behave differently from a plain one? The formulation can change where and when drug is released. The drug p K a alone does not determine that release, total absorption or clinical safety. A small original aspirin study found different absorption kinetics between formulations. Studies of local surface damage and serious gastrointestinal complications examine different outcomes. We will use an equilibrium model for ionisation without treating it as a clinical prediction.');
  const forms=set('concept-forms',{heading:'Two forms in a weak-acid equilibrium',body:'HA ⇌ H⁺ + A⁻. Changing pH changes their equilibrium ratio.',bullets:bullets(['Unionised HA is often more favourable for passive lipid diffusion.','Charged A⁻ usually crosses a lipid bilayer less readily by that route.','Other transport routes, formulation and physiological conditions matter.']),secondary:'The animation is a simplified passive-diffusion illustration, not a complete absorption model.',callout:'Ionisation fraction is not absorption fraction.',caption:'No rate, total uptake or clinical outcome is predicted.'},'A single-site weak acid is represented by H A in equilibrium with hydrogen ion and A minus. The unionised form often diffuses through a lipid membrane more readily than the charged form. This is a simplified comparison of one transport route. It does not mean every unionised molecule crosses or that ions can never be transported. Dissolution, formulation, surface area, transit and other routes can matter. The equilibrium fraction is not the fraction of an administered dose absorbed.');
  forms.diagram.props={mode:'forms',reviewedMedicine:true};
  const hh=set('concept-hh',{heading:'Use the ratio under stated assumptions',body:'For an ideal dilute, single-site weak acid: [A⁻]/[HA] = 10^(pH − pKa).',bullets:bullets(['pH = pKa gives equal concentrations.','One pH unit above pKa gives a ratio of 10:1.','Fraction A⁻ = r/(1+r); fraction HA = 1/(1+r).']),secondary:'Concentration ratios approximate activity ratios under this model. Particle counts are rounded illustrations.',callout:'A ratio needs conversion before it becomes a percentage.',caption:'No absorption percentage follows from this equation.'},'For this ideal dilute model, the Henderson-Hasselbalch relation gives the concentration ratio of A minus to H A as ten raised to p H minus p K a. Equal p H and p K a give equal concentrations. One p H unit above gives a ten-to-one ratio, not one hundred percent ionisation. If the ratio is r, the ionised fraction is r divided by one plus r. The unionised fraction is one divided by one plus r. This single-site equilibrium calculation does not predict absorption.');
  hh.diagram.props={mode:'hh',reviewedMedicine:true};
  const compare=set('concept-aspirin',{heading:'Compare two stated model conditions',body:'Use an illustrative pKa of 3.5 at pH 1.5 and 6.5 for a single-site weak acid.',bullets:bullets(['pH 1.5: r = 0.01; HA ≈ 99.01%.','pH 6.5: r = 1000; A⁻ ≈ 99.90%.','These are equilibrium fractions, not measured absorption or bioavailability.']),secondary:'The displayed populations round a continuous fraction to a small number of particles.',callout:'State the chosen pH, not a universal stomach or intestine value.',caption:'Ideal teaching calculation using supplied pKa 3.5.'},'Compare two chosen conditions using a supplied illustrative p K a of three point five. At p H one point five, the ratio of A minus to H A is nought point zero one. The unionised fraction is one divided by one point zero one, about ninety-nine point zero one percent. At p H six point five, the ratio is one thousand and the ionised fraction is about ninety-nine point nine zero percent. These are equilibrium fractions at specified conditions, not universal organ values or measured absorption percentages.');
  compare.diagram.props={mode:'compare',reviewedMedicine:true,pKa:3.5,stomachRange:[1,2],intestineRange:[6,7],stomachPH:1.5,intestinePH:6.5};
  set('worked-example',{heading:'Convert ratio to fraction',question:'An ideal single-site weak acid has supplied pKa = 3.5. At pH = 1.5, calculate [A⁻]/[HA] and the percentage present as HA.',coachNote:'Use the supplied model values; do not infer an absorption percentage.',steps:['pH − pKa = 1.5 − 3.5 = −2.0','r = [A⁻]/[HA] = 10⁻² = 0.01','Fraction HA = 1/(1 + r) = 1/1.01','HA ≈ 99.01%; A⁻ ≈ 0.99%','The percentages describe chemical forms at equilibrium.'],caption:'A ratio of 0.01 gives about 99.01% HA, not 99.7%.'},'Subtract p K a from p H: one point five minus three point five is minus two. The ratio of A minus to H A is ten to the minus two, or nought point zero one. The total consists of both forms, so divide one by one plus that ratio. The unionised fraction is about nought point nine nine zero one, or ninety-nine point zero one percent. The remaining nought point nine nine percent is ionised. Neither number is an absorption percentage.');
  set('definition',{heading:'Keep the measured quantities distinct',bullets:bullets(['Solubility: equilibrium dissolved concentration under specified conditions.','Dissolution rate: how quickly material enters solution.','Permeability: transport across a specified barrier under specified conditions.','Systemic bioavailability: fraction of a dose reaching systemic circulation unchanged.']),callout:'Different quantities need different evidence.',caption:'Ionisation can affect behaviour without determining every outcome.'},'Solubility describes an equilibrium dissolved concentration under specified conditions. Dissolution rate describes how quickly material enters solution. Permeability concerns transport across a specified barrier. Systemic bioavailability concerns how much of a dose reaches systemic circulation unchanged. These are related but different quantities. Ionisation may influence them, but p H and p K a alone cannot supply all four. State which quantity a measurement or model actually addresses.');
  const salts=set('concept-salts',{heading:'Salt effects require conditions and evidence',body:'Illustrative data: a free acid has solubility 3 g/L and a salt form 30 g/L under the same stated comparison conditions.',bullets:bullets(['For these supplied values, the ratio is 30/3 = 10.','The numbers are invented teaching data, not measured aspirin values.','Salt formation does not guarantee increased solubility or bioavailability.']),secondary:'Solid form, solvent, pH and temperature matter. Compare pKa values in the same solvent and temperature.',callout:'Use measured data for a real material.',caption:'Illustrative tenfold comparison; no universal salt rule.'},'Salt formation can change solubility, but it is not a universal fix. Consider invented teaching data under the same comparison conditions: three grams per litre for a free acid and thirty for a salt form. The ratio is ten. These are not measured aspirin solubilities. A real comparison needs the particular solid forms, solvent, p H and temperature. A solubility increase would not itself guarantee greater bioavailability. Separately, within the same solvent and temperature, a lower p K a denotes a stronger acid.');
  salts.diagram.props={mode:'salts',reviewedMedicine:true,acidSolubility:3,saltSolubility:30};
  set('misconception',{heading:'Do not turn a fraction into a clinical verdict',body:'Higher pH favours A⁻ for this weak acid. That does not prove where most of a dose is absorbed.',secondary:'Nor do ionisation, a salt form or an enteric coating establish clinical safety.',mistakeTag:'Equilibrium chemistry is only part of the system',callout:'Name the model and its limits.',caption:'Avoid universal claims about uptake or protection.'},'For a weak acid, increasing p H favours the deprotonated form A minus. Do not reverse that direction. But also avoid the larger mistake of turning an equilibrium fraction into a clinical verdict. The location and extent of absorption depend on more than ionisation. A salt form or coating likewise does not prove better bioavailability or protection from serious harm. Use chemical models for the questions they can answer and demand evidence for the remaining claims.');
  response={minimumThinkingSeconds:40,promptText:'Three single-site weak acids have supplied p K a values of two point one, four point eight and six point two, measured in the same solvent at the same temperature. Which is strongest? For the acid with p K a four point eight, what is the A minus to H A ratio at p H four point eight? Does this establish its bioavailability? Pause and decide.',answerText:'The acid with p K a two point one is strongest under the stated comparison conditions. For the acid with p K a four point eight at the same p H, the ratio is one to one, so each form contributes fifty percent in the ideal model. This does not establish systemic bioavailability. That needs additional evidence about the formulation and biological system.'};
  set('quick-check',{heading:'Strength, ratio and limits',question:'At the same solvent and temperature, compare pKa 2.1, 4.8 and 6.2. Which acid is strongest? At pH = pKa = 4.8, what is [A⁻]/[HA], and what remains unknown about bioavailability?',pausePrompt:'Pause: rank strength, calculate the ratio, then state the limit.',answerSteps:['pKa 2.1: strongest acid in this stated comparison.','At pH = pKa, r = 1 and each form is 50% in the model.','Systemic bioavailability is not established by this equilibrium ratio.'],caption:'Compare matching conditions and distinguish the predicted quantity.'},response.promptText+' '+response.answerText);
  set('summary',{heading:'A useful model with a clear boundary',points:['Use the supplied pH and pKa under stated conditions.','Calculate r = 10^(pH − pKa), then convert to fractions.','Fractions describe equilibrium forms, not dose absorption.','Solubility data require stated conditions and real measurements.','Formulation and clinical outcomes need separate evidence.'],finalPrompt:'What does the calculation predict, and what does it leave unknown?',caption:'Chemistry enrichment; clinical and curriculum review remain separate.'},'Use supplied p H and p K a values under stated model assumptions. Calculate the ratio, then convert it to fractions of the total. Those fractions describe chemical forms at equilibrium. They do not measure dose absorption or systemic bioavailability. Real solubility comparisons need defined conditions and measurements. Formulation and clinical outcomes require separate evidence. The most useful answer states both what the calculation predicts and what it cannot establish.');
 }
 const pacing=draft.scenes.map(scene=>{const old=original.scenes.find(s=>s.id===scene.id);const budget=getVoiceoverBudget({text:scene.voiceover?.text??'',durationInFrames:old.durationInFrames,fps:draft.fps});scene.durationInFrames=Math.max(old.durationInFrames,budget.requiredFrames+(scene.id==='quick-check'?response.minimumThinkingSeconds*draft.fps:90));return {scene:scene.id,inheritedFrames:old.durationInFrames,proposedFrames:scene.durationInFrames,status:'unmeasured source estimate; rebuild animation cues and review visual fit',...(scene.id==='quick-check'?{response}:{})};});
 assertUnvoicedMedicineDraft(draft);
 const before=new Map(stringFields(original).map(f=>[f.field,f.text]));
 const changes=stringFields(draft).filter(f=>before.get(f.field)!==f.text).map(f=>({field:f.field,before:before.get(f.field)??null,after:f.text}));
 return {draft,pacing,changes,originalMapping:{syllabusVersion:original.syllabusVersion,syllabusModule:original.syllabusModule,syllabusDotPoints:original.syllabusDotPoints,nesaOutcomes:original.nesaOutcomes}};
}
export function medicineArtifacts(name,bytes){
 const r=medicineDraft(name,bytes),links={sourceSha256:medicineSources[name],draftSha256:hash(JSON.stringify(r.draft,null,2)+'\n')};
 const takes=r.draft.scenes.flatMap(s=>{if(!s.voiceover)return [];const response=r.pacing.find(p=>p.scene===s.id).response;return (response?[['prompt',response.promptText],['answer',response.answerText]]:[['narration',s.voiceover.text]]).map(([phase,text])=>({scene:s.id,phase,text,textSha256:hash(text),...links,audioFile:null,status:'unapproved text candidate'}));});
 return {draft:r.draft,changes:r.changes,pacing:{...links,scenes:r.pacing},takes:{...links,generationAuthorised:false,audioGenerated:false,voiceId:null,modelId:null,settings:null,takes},review:{...links,sources:medicineEvidence,originalMapping:r.originalMapping,curriculumStatus:'Enrichment only. Original mapping retained here as disputed evidence; it is not certified.',scienceApproval:false,registered:false,rendered:false,catalogueChanged:false,holds:['Teacher and specialist science review required.','Original image content unavailable for inspection.','New and legacy medicine content remain held from release.','Opt-in diagram text has component markup tests only, not actual visual-fit or playback QA.','Rebuild timing, audio, alignments, captions and response assembly after source approval.']}};
}
export function validateMedicineArtifacts(name,bytes,artifacts){assertUnvoicedMedicineDraft(artifacts.draft);assert.deepEqual(artifacts,medicineArtifacts(name,bytes),'Medicine package differs from the source-reviewed candidate');return {scenes:artifacts.draft.scenes.length,narratedScenes:artifacts.draft.scenes.filter(s=>s.voiceover).length,takes:artifacts.takes.takes.length};}
