import {staticFile} from 'remotion';

export const ASSETS = {
	// ── Lesson title heroes ─────────────────────────────────────────────────
	heroPartA:            staticFile('assets/heroPartA.png'),

	// ── M2 L1 custom illustrations ──────────────────────────────────────────
	carbon12MolarMassBalance: staticFile('assets/carbon-12-molar-mass-balance.png'),
	waterMoleculePremium: staticFile('assets/water-molecule-premium.png'),
	moleSwarm: staticFile('assets/mole-swarm.png'),
	formulaBridge: staticFile('assets/formula-bridge.png'),
	moleCountingMetaphor: staticFile('assets/mole-counting-metaphor.png'),
	examTrapStamp: staticFile('assets/exam-trap-stamp.png'),

	// ── Science illustrations ──────────────────────────────────────────────
	waterMolecule:        staticFile('assets/water-molecule.png'),
	waterMoleculeClassic: staticFile('assets/water-molecule-classic.png'),
	dnaHelix:             staticFile('assets/dna-helix.png'),
	dnaHelixPurple:       staticFile('assets/dna-helix-purple.png'),
	bubbles:              staticFile('assets/bubbles.png'),
	elementC:             staticFile('assets/element-c.png'),

	// ── World / nature ─────────────────────────────────────────────────────
	sun:     staticFile('assets/sun.png'),
	volcano: staticFile('assets/volcano.png'),
	earth:   staticFile('assets/earth.png'),
	leaf:    staticFile('assets/leaf.png'),

	// ── Biology ────────────────────────────────────────────────────────────
	virus:     staticFile('assets/virus.png'),
	plantCell: staticFile('assets/plant-cell.png'),
	neuron:    staticFile('assets/neuron.png'),

	// ── Backgrounds ────────────────────────────────────────────────────────
	waterDropletsBg: staticFile('assets/water-droplets-bg.png'),

	// ── Lab equipment ──────────────────────────────────────────────────────
	beaker:          staticFile('assets/Beaker.png'),
	flask:           staticFile('assets/Flask.png'),
	volumetricFlask: staticFile('assets/Volumetric flask.png'),
	bunsenBurner:    staticFile('assets/bunsen burner.png'),
	testtube:        staticFile('assets/testtube.png'),
	testtubeRack:    staticFile('assets/testtube in mini rack.png'),
	scale:           staticFile('assets/scale.png'),
	magnifyingGlass: staticFile('assets/magnifying glass.png'),
	microPipette:    staticFile('assets/micro pipette.png'),
	metalCoil:       staticFile('assets/metal coil.png'),
	tripodGauze:     staticFile('assets/tripod with gauze.png'),
	goldCoin:        staticFile('assets/gold coin.png'),
	pendulum:        staticFile('assets/pendulum.png'),
	mole:            staticFile('assets/mole.png'),
	salt:            staticFile('assets/Salt.png'),
	rice:            staticFile('assets/Rice.png'),
	character:       staticFile('assets/Character.png'),

	// ── HSCScience pulled assets ───────────────────────────────────────────
	chemM2Hero:              staticFile('assets/hscscience/chem-m2-hero.webp'),
	chemistrySubjectIcon:    staticFile('assets/hscscience/chemistry.svg'),
	standardSolutionPrep:    staticFile('assets/hscscience/l07-standard-solution-prep.svg'),
	gravimetricApparatus:    staticFile('assets/hscscience/l09-gravimetric-apparatus.svg'),
	errorApparatus:          staticFile('assets/hscscience/l18-error-apparatus.svg'),
	vennDiagram:             staticFile('assets/hscscience/venn-diagram.svg'),
	flowchartHorizontal:     staticFile('assets/hscscience/flowchart-horizontal.svg'),
	comparisonCards:         staticFile('assets/hscscience/comparison-cards-2.svg'),

	// ── Lesson 2 generated images ──────────────────────────────────────────
	l2HookBalance:           staticFile('assets/hscscience/generated/lesson-2-molar-mass/hook-balance-moles-grams.png'),
	l2MarginaliaBridge:      staticFile('assets/hscscience/generated/lesson-2-molar-mass/marginalia-bridge-particles-grams.png'),
	l2ConceptPeriodicTable:  staticFile('assets/hscscience/generated/lesson-2-molar-mass/concept-periodic-table-strip.png'),
	l2DefinitionUnitsCube:   staticFile('assets/hscscience/generated/lesson-2-molar-mass/definition-units-cube.png'),
	l2LabFootageBalance:     staticFile('assets/hscscience/generated/lesson-2-molar-mass/lab-footage-balance-beaker.png'),
	l2FormulaEquation:       staticFile('assets/hscscience/generated/lesson-2-molar-mass/formula-equation-particles.png'),
	l2WorkedExampleCO2:      staticFile('assets/hscscience/generated/lesson-2-molar-mass/worked-example-co2-builder.png'),
	l2MisconceptionScales:   staticFile('assets/hscscience/generated/lesson-2-molar-mass/misconception-two-scales-comparison.png'),
	l2QuickCheckWater:       staticFile('assets/hscscience/generated/lesson-2-molar-mass/quick-check-water-molecule-masses.png'),
	l2SummaryBadges:         staticFile('assets/hscscience/generated/lesson-2-molar-mass/summary-key-ideas-badge-set.png'),

	// ── Lesson 3 generated images (Empirical & Molecular Formulas) ─────────
	l3EmpiricalVsMolecular:  staticFile('assets/hscscience/generated/lesson-3-empirical-molecular/empirical-vs-molecular.png'),
	l3MassBreakdown100g:     staticFile('assets/hscscience/generated/lesson-3-empirical-molecular/mass-breakdown-100g.png'),

	// ── Lesson 4 generated images (Gases & Molar Volume) ───────────────────
	// Note: concept (3 flasks) + formula (triangle) are now CODED diagrams
	// (gasVolumeComparison / bullets), not generated images. Only the STP-vs-
	// SATP worked-example comparison remains a generated image.
	l4TwoConditionsCompare:  staticFile('assets/hscscience/generated/lesson-4-gases-molar-volume/two-conditions-compare.png'),

	// ── Lesson 5 generated images (Mole Calculations Consolidation) ────────
	l5MoleHub:               staticFile('assets/hscscience/generated/lesson-5-mole-consolidation/mole-hub.png'),
	l5FormulaChain:          staticFile('assets/hscscience/generated/lesson-5-mole-consolidation/formula-chain.png'),
	l5MysteryGas:            staticFile('assets/hscscience/generated/lesson-5-mole-consolidation/mystery-gas.png'),

	// ── Lessons 6–20 concept images (one didactic still per lesson) ────────
	// Note: L6, L10, L13, L17, L18 now use CODED diagrams, not images.
	l7DilutionConcept:       staticFile('assets/hscscience/generated/lesson-7-standard-solutions/dilution-concept.png'),
	l8PurityPpm:             staticFile('assets/hscscience/generated/lesson-8-concentration-context/purity-ppm.png'),
	l9GravimetricFlow:       staticFile('assets/hscscience/generated/lesson-9-gravimetric/gravimetric-flow.png'),
	l11MoleRatioRecipe:      staticFile('assets/hscscience/generated/lesson-11-mole-ratios/mole-ratio-recipe.png'),
	l12MassMassBridge:       staticFile('assets/hscscience/generated/lesson-12-mass-mass/mass-mass-bridge.png'),
	l14YieldPurity:          staticFile('assets/hscscience/generated/lesson-14-yield-purity/yield-purity.png'),
	l15GasStoich:            staticFile('assets/hscscience/generated/lesson-15-gas-stoich/gas-stoich.png'),
	l16SolutionStoich:       staticFile('assets/hscscience/generated/lesson-16-solution-stoich/solution-stoich.png'),
	l19ExamStrategy:         staticFile('assets/hscscience/generated/lesson-19-synthesis/exam-strategy.png'),
	l20MoleHub:              staticFile('assets/hscscience/generated/lesson-20-review/mole-hub.png'),

	// ── Module 1 generated images (site-aligned rebuild) ───────────────────
	m1L1SaltWaterBronze:        staticFile('assets/hscscience/generated/lesson-1-classification/salt-water-bronze.png'),
	m1L3FiltrationFunnel:       staticFile('assets/hscscience/generated/lesson-3-separation/filtration-funnel.png'),
	// L7 ionic + L8 metallic now use the coded latticeVsElectronSea diagram (no image).
	l11AdditionPolymerisation:  staticFile('assets/hscscience/generated/lesson-11-polymers/addition-polymerisation.png'),
	l11CondensationPolymerisation: staticFile('assets/hscscience/generated/lesson-11-polymers/condensation-polymerisation.png'),
	l12DissolvingEnergyBalance: staticFile('assets/hscscience/generated/lesson-12-solubility/dissolving-energy-balance.png'),
	l12HydrationOfIons:         staticFile('assets/hscscience/generated/lesson-12-solubility/hydration-of-ions.png'),
	l13AtomicModelTimeline:     staticFile('assets/hscscience/generated/lesson-13-atomic-models/atomic-model-timeline.png'),
	l14IsotopesComparison:      staticFile('assets/hscscience/generated/lesson-14-isotopes/isotopes-comparison.png'),
	l15PeriodicTableOrganisation: staticFile('assets/hscscience/generated/lesson-15-periodic-table/periodic-table-organisation.png'),
	l16AufbauDiagonal:          staticFile('assets/hscscience/generated/lesson-16-electron-config/aufbau-diagonal.png'),
	l18ElectronegativityTrend:  staticFile('assets/hscscience/generated/lesson-18-electronegativity/electronegativity-trend.png'),
	l19TransitionMetalIons:     staticFile('assets/hscscience/generated/lesson-19-electron-config-behaviour/transition-metal-ions.png'),

	// ── Module 4 hook images (lean rework: 1 hook image per lesson) ────────
	m4l1HookPacks:           staticFile('assets/hscscience/generated/chem-y11-m4/l1/hook-packs.png'),
	m4l2HookFuel:            staticFile('assets/hscscience/generated/chem-y11-m4/l2/hook-fuel.png'),
	m4l3HookCup:             staticFile('assets/hscscience/generated/chem-y11-m4/l3/hook-cup.png'),
	m4l4HookPacks:           staticFile('assets/hscscience/generated/chem-y11-m4/l4/hook-packs.png'),
	m4l5HookConverter:       staticFile('assets/hscscience/generated/chem-y11-m4/l5/hook-converter.png'),
	m4l6HookHaber:           staticFile('assets/hscscience/generated/chem-y11-m4/l6/hook-haber.png'),
	m4l7HookApollo:          staticFile('assets/hscscience/generated/chem-y11-m4/l7/hook-apollo.png'),
	m4l8HookIndirectPath:    staticFile('assets/hscscience/generated/chem-y11-m4/l8/hook-indirect-path.png'),
	m4l9HookCycle:           staticFile('assets/hscscience/generated/chem-y11-m4/l9/hook-cycle.png'),
	m4l10HookToolbox:        staticFile('assets/hscscience/generated/chem-y11-m4/l10/hook-toolbox.png'),
	m4l11HookGlass:          staticFile('assets/hscscience/generated/chem-y11-m4/l11/hook-glass.png'),
	m4l12HookFromSign:       staticFile('assets/hscscience/generated/chem-y11-m4/l12/hook-from-sign.png'),
	m4l13HookGoNoGo:         staticFile('assets/hscscience/generated/chem-y11-m4/l13/hook-go-no-go.png'),
	m4cp1ColdOpenScenarios:  staticFile('assets/hscscience/generated/chem-y11-m4/cp1/cold-open-scenarios.png'),
	m4cp2ColdOpenScenarios:  staticFile('assets/hscscience/generated/chem-y11-m4/cp2/cold-open-scenarios.png'),
	m4cp3ColdOpenScenarios:  staticFile('assets/hscscience/generated/chem-y11-m4/cp3/cold-open-scenarios.png'),

	// ── Chemistry Y11 Module 3 generated images ───────────────────────────
	l1HookFireIce:                    staticFile('assets/hscscience/chem-y11-m3/l1/hook-fire-ice.png'),
	l1DefinitionFiveIndicators:       staticFile('assets/hscscience/chem-y11-m3/l1/definition-five-indicators.png'),
	l1MarginaliaAtomBalls:            staticFile('assets/hscscience/chem-y11-m3/l1/marginalia-atom-balls.png'),
	l1WorkedZincAcid:                 staticFile('assets/hscscience/chem-y11-m3/l1/worked-zinc-acid.png'),
	l1MisconceptionAmmoniumNitrate:   staticFile('assets/hscscience/chem-y11-m3/l1/misconception-ammonium-nitrate.png'),
	l1LabFootageFireworks:            staticFile('assets/hscscience/chem-y11-m3/l1/lab-footage-fireworks.png'),
	l1QuickCheckMgCuSO4:              staticFile('assets/hscscience/chem-y11-m3/l1/quick-check-mg-cuso4.png'),
	l1SummaryBadges:                  staticFile('assets/hscscience/chem-y11-m3/shared/summary-badges.png'),
	lSummaryBadges:                   staticFile('assets/hscscience/chem-y11-m3/shared/summary-badges.png'),

	l2HookBeirut:                     staticFile('assets/hscscience/chem-y11-m3/l2/hook-beirut.png'),
	l2DefinitionPatternMatch:         staticFile('assets/hscscience/chem-y11-m3/l2/definition-pattern-match.png'),
	l2MarginaliaBeirutPathways:       staticFile('assets/hscscience/chem-y11-m3/l2/marginalia-beirut-pathways.png'),
	l2WorkedMgBurns:                  staticFile('assets/hscscience/chem-y11-m3/l2/worked-mg-burns.png'),
	l2MisconceptionElementOnly:       staticFile('assets/hscscience/chem-y11-m3/l2/misconception-element-only.png'),
	l2LabFootageCuCO3:                staticFile('assets/hscscience/chem-y11-m3/l2/lab-footage-cuco3.png'),
	l2QuickCheckH2O2:                 staticFile('assets/hscscience/chem-y11-m3/l2/quick-check-h2o2.png'),

	l3HookBariumMeal:                 staticFile('assets/hscscience/chem-y11-m3/l3/hook-barium-meal.png'),
	l3DefinitionNAGSAG:               staticFile('assets/hscscience/chem-y11-m3/l3/definition-nagsag.png'),
	l3MarginaliaEquationLevels:       staticFile('assets/hscscience/chem-y11-m3/l3/marginalia-equation-levels.png'),
	l3WorkedBaSO4:                    staticFile('assets/hscscience/chem-y11-m3/l3/worked-baso4.png'),
	l3MisconceptionLatticeEnergy:     staticFile('assets/hscscience/chem-y11-m3/l3/misconception-lattice-energy.png'),
	l3LabFootageAgCl:                 staticFile('assets/hscscience/chem-y11-m3/l3/lab-footage-agcl.png'),
	l3QuickCheckPbI2:                 staticFile('assets/hscscience/chem-y11-m3/l3/quick-check-pbi2.png'),
	l3SummaryBadges:                  staticFile('assets/hscscience/chem-y11-m3/shared/summary-badges.png'),

	l4HookBushfire:                   staticFile('assets/hscscience/chem-y11-m3/l4/hook-bushfire.png'),
	l4DefinitionCOHaemoglobin:        staticFile('assets/hscscience/chem-y11-m3/l4/definition-co-haemoglobin.png'),
	l4MarginaliaBunsenFlames:         staticFile('assets/hscscience/chem-y11-m3/l4/marginalia-bunsen-flames.png'),
	l4WorkedButane:                   staticFile('assets/hscscience/chem-y11-m3/l4/worked-butane.png'),
	l4MisconceptionLessCO2:           staticFile('assets/hscscience/chem-y11-m3/l4/misconception-less-co2.png'),
	l4LabFootageFlames:               staticFile('assets/hscscience/chem-y11-m3/l4/lab-footage-flames.png'),
	l4QuickCheckMethane:              staticFile('assets/hscscience/chem-y11-m3/l4/quick-check-methane.png'),
	l4SummaryBadges:                  staticFile('assets/hscscience/chem-y11-m3/shared/summary-badges.png'),

	l5HookAntacids:                   staticFile('assets/hscscience/chem-y11-m3/l5/hook-antacids.png'),
	l5DefinitionSWC:                  staticFile('assets/hscscience/chem-y11-m3/l5/definition-swc.png'),
	l5MarginaliaAntacidChoice:        staticFile('assets/hscscience/chem-y11-m3/l5/marginalia-antacid-choice.png'),
	l5WorkedHClNa2CO3:                staticFile('assets/hscscience/chem-y11-m3/l5/worked-hcl-na2co3.png'),
	l5MisconceptionBronstedLowry:     staticFile('assets/hscscience/chem-y11-m3/l5/misconception-bronsted-lowry.png'),
	l5LabFootageTumsVinegar:          staticFile('assets/hscscience/chem-y11-m3/l5/lab-footage-tums-vinegar.png'),
	l5QuickCheckMgOH2:                staticFile('assets/hscscience/chem-y11-m3/l5/quick-check-mgoh2.png'),
	l5SummaryBadges:                  staticFile('assets/hscscience/chem-y11-m3/shared/summary-badges.png'),

	// ── Lesson 6 ────────────────────────────────────────────────────────────
	l6HookCycad:                      staticFile('assets/hscscience/chem-y11-m3/l6/l6HookCycad.png'),
	l6ConceptLeaching:                staticFile('assets/hscscience/chem-y11-m3/l6/l6ConceptLeaching.png'),
	l6DefinitionProcesses:            staticFile('assets/hscscience/chem-y11-m3/l6/l6DefinitionProcesses.png'),
	l6WorkedExampleBalancing:         staticFile('assets/hscscience/chem-y11-m3/l6/l6WorkedExampleBalancing.png'),
	l6MisconceptionKnowledge:         staticFile('assets/hscscience/chem-y11-m3/l6/l6MisconceptionKnowledge.png'),
	l6QuickCheckBalancing:            staticFile('assets/hscscience/chem-y11-m3/l6/l6QuickCheckBalancing.png'),
	l6SummaryDetoxification:          staticFile('assets/hscscience/chem-y11-m3/l6/l6SummaryDetoxification.png'),

	// ── Lesson 7 ────────────────────────────────────────────────────────────
	l7HookHarbourBridge:              staticFile('assets/hscscience/chem-y11-m3/l7/l7HookHarbourBridge.png'),
	l7DefinitionActivitySeries:       staticFile('assets/hscscience/chem-y11-m3/l7/l7DefinitionActivitySeries.png'),
	l7MarginaliaSacrificial:          staticFile('assets/hscscience/chem-y11-m3/l7/l7MarginaliaSacrificial.png'),
	l7WorkedDisplacement:             staticFile('assets/hscscience/chem-y11-m3/l7/l7WorkedDisplacement.png'),
	l7MisconceptionAluminium:         staticFile('assets/hscscience/chem-y11-m3/l7/l7MisconceptionAluminium.png'),
	l7LabFootageAcidReactions:        staticFile('assets/hscscience/chem-y11-m3/l7/l7LabFootageAcidReactions.png'),
	l7QuickCheckFeCu:                 staticFile('assets/hscscience/chem-y11-m3/l7/l7QuickCheckFeCu.png'),
	l7SummaryActivitySeries:          staticFile('assets/hscscience/chem-y11-m3/l7/l7SummaryActivitySeries.png'),

	// ── Lesson 8 ────────────────────────────────────────────────────────────
	l8HookBleach:                     staticFile('assets/hscscience/chem-y11-m3/l8/l8HookBleach.png'),
	l8ConceptElectronTransfer:        staticFile('assets/hscscience/chem-y11-m3/l8/l8ConceptElectronTransfer.png'),
	l8DefinitionOxidationRules:       staticFile('assets/hscscience/chem-y11-m3/l8/l8DefinitionOxidationRules.png'),
	l8MarginaliaHalfEquation:         staticFile('assets/hscscience/chem-y11-m3/l8/l8MarginaliaHalfEquation.png'),
	l8WorkedExampleMnO4:              staticFile('assets/hscscience/chem-y11-m3/l8/l8WorkedExampleMnO4.png'),
	l8MisconceptionBleach:            staticFile('assets/hscscience/chem-y11-m3/l8/l8MisconceptionBleach.png'),
	l8QuickCheckCr2O7:                staticFile('assets/hscscience/chem-y11-m3/l8/l8QuickCheckCr2O7.png'),
	l8SummaryRedox:                   staticFile('assets/hscscience/chem-y11-m3/l8/l8SummaryRedox.png'),

	// ── Lesson 9 ────────────────────────────────────────────────────────────
	l9HookBattery:                    staticFile('assets/hscscience/chem-y11-m3/l9/l9HookBattery.png'),
	l9DefinitionReductionPotentials:  staticFile('assets/hscscience/chem-y11-m3/l9/l9DefinitionReductionPotentials.png'),
	l9WorkedExampleZnCu:              staticFile('assets/hscscience/chem-y11-m3/l9/l9WorkedExampleZnCu.png'),
	l9MisconceptionSaltBridge:        staticFile('assets/hscscience/chem-y11-m3/l9/l9MisconceptionSaltBridge.png'),
	l9QuickCheckFeNi:                 staticFile('assets/hscscience/chem-y11-m3/l9/l9QuickCheckFeNi.png'),
	l9SummaryGalvanicCell:            staticFile('assets/hscscience/chem-y11-m3/l9/l9SummaryGalvanicCell.png'),

	// ── Lesson 10 ───────────────────────────────────────────────────────────
	l10HookCopperAcid:                staticFile('assets/hscscience/chem-y11-m3/l10/l10HookCopperAcid.png'),
	l10DefinitionAcidReactivity:      staticFile('assets/hscscience/chem-y11-m3/l10/l10DefinitionAcidReactivity.png'),
	l10WorkedExampleCuZn:             staticFile('assets/hscscience/chem-y11-m3/l10/l10WorkedExampleCuZn.png'),
	l10MisconceptionCopperAcid:       staticFile('assets/hscscience/chem-y11-m3/l10/l10MisconceptionCopperAcid.png'),
	l10QuickCheckMgSn:                staticFile('assets/hscscience/chem-y11-m3/l10/l10QuickCheckMgSn.png'),
	l10SummaryInertElectrodes:        staticFile('assets/hscscience/chem-y11-m3/l10/l10SummaryInertElectrodes.png'),

	// ── Lesson 11 ───────────────────────────────────────────────────────────
	l11HookGlowStick:                 staticFile('assets/hscscience/chem-y11-m3/l11/l11HookGlowStick.png'),
	l11ConceptBilliards:              staticFile('assets/hscscience/chem-y11-m3/l11/l11ConceptBilliards.png'),
	l11WorkedExampleEnergyProfile:    staticFile('assets/hscscience/chem-y11-m3/l11/l11WorkedExampleEnergyProfile.png'),
	l11MisconceptionTemperature:      staticFile('assets/hscscience/chem-y11-m3/l11/l11MisconceptionTemperature.png'),
	l11QuickCheckEnergyProfile:       staticFile('assets/hscscience/chem-y11-m3/l11/l11QuickCheckEnergyProfile.png'),
	l11SummaryCollisionTheory:        staticFile('assets/hscscience/chem-y11-m3/l11/l11SummaryCollisionTheory.png'),

	// ── Lesson 12 ───────────────────────────────────────────────────────────
	l12HookCooking:                   staticFile('assets/hscscience/chem-y11-m3/l12/l12HookCooking.png'),
	l12DefinitionFactors:             staticFile('assets/hscscience/chem-y11-m3/l12/l12DefinitionFactors.png'),
	l12WorkedExampleScenarios:        staticFile('assets/hscscience/chem-y11-m3/l12/l12WorkedExampleScenarios.png'),
	l12MisconceptionCatalyst:         staticFile('assets/hscscience/chem-y11-m3/l12/l12MisconceptionCatalyst.png'),
	l12QuickCheckMagnesium:           staticFile('assets/hscscience/chem-y11-m3/l12/l12QuickCheckMagnesium.png'),
	l12SummaryFactors:                staticFile('assets/hscscience/chem-y11-m3/l12/l12SummaryFactors.png'),

	// ── Checkpoint 1 ────────────────────────────────────────────────────────
	cp1ColdOpenScenarios:             staticFile('assets/hscscience/chem-y11-m3/cp1/cp1ColdOpenScenarios.png'),
	cp1DecisionTree:                  staticFile('assets/hscscience/chem-y11-m3/cp1/cp1DecisionTree.png'),
	cp1Walkthrough1Precipitation:     staticFile('assets/hscscience/chem-y11-m3/cp1/cp1Walkthrough1Precipitation.png'),
	cp1Walkthrough2Combustion:        staticFile('assets/hscscience/chem-y11-m3/cp1/cp1Walkthrough2Combustion.png'),
	cp1Walkthrough3Carbonate:         staticFile('assets/hscscience/chem-y11-m3/cp1/cp1Walkthrough3Carbonate.png'),
	cp1ExamPitfalls:                  staticFile('assets/hscscience/chem-y11-m3/cp1/cp1ExamPitfalls.png'),
	cp1QuickCheckBossFight:           staticFile('assets/hscscience/chem-y11-m3/cp1/cp1QuickCheckBossFight.png'),
	cp1SummaryClosing:                staticFile('assets/hscscience/chem-y11-m3/cp1/cp1SummaryClosing.png'),

	// ── Checkpoint 2 ────────────────────────────────────────────────────────
	cp2ColdOpenScenarios:             staticFile('assets/hscscience/chem-y11-m3/cp2/cp2ColdOpenScenarios.png'),
	cp2DecisionTree:                  staticFile('assets/hscscience/chem-y11-m3/cp2/cp2DecisionTree.png'),
	cp2Walkthrough1Redox:             staticFile('assets/hscscience/chem-y11-m3/cp2/cp2Walkthrough1Redox.png'),
	cp2Walkthrough2Cell:              staticFile('assets/hscscience/chem-y11-m3/cp2/cp2Walkthrough2Cell.png'),
	cp2Walkthrough3Acid:              staticFile('assets/hscscience/chem-y11-m3/cp2/cp2Walkthrough3Acid.png'),
	cp2ExamPitfalls:                  staticFile('assets/hscscience/chem-y11-m3/cp2/cp2ExamPitfalls.png'),
	cp2QuickCheckBossFight:           staticFile('assets/hscscience/chem-y11-m3/cp2/cp2QuickCheckBossFight.png'),
	cp2SummaryClosing:                staticFile('assets/hscscience/chem-y11-m3/cp2/cp2SummaryClosing.png'),

	// ── Checkpoint 3 ────────────────────────────────────────────────────────
	cp3ColdOpenScenarios:             staticFile('assets/hscscience/chem-y11-m3/cp3/cp3ColdOpenScenarios.png'),
	cp3DecisionTree:                  staticFile('assets/hscscience/chem-y11-m3/cp3/cp3DecisionTree.png'),
	cp3Walkthrough1EnergyProfile:     staticFile('assets/hscscience/chem-y11-m3/cp3/cp3Walkthrough1EnergyProfile.png'),
	cp3Walkthrough2Boltzmann:         staticFile('assets/hscscience/chem-y11-m3/cp3/cp3Walkthrough2Boltzmann.png'),
	cp3Walkthrough3Factors:           staticFile('assets/hscscience/chem-y11-m3/cp3/cp3Walkthrough3Factors.png'),
	cp3ExamPitfalls:                  staticFile('assets/hscscience/chem-y11-m3/cp3/cp3ExamPitfalls.png'),
	cp3QuickCheckBossFight:           staticFile('assets/hscscience/chem-y11-m3/cp3/cp3QuickCheckBossFight.png'),
	cp3SummaryClosing:                staticFile('assets/hscscience/chem-y11-m3/cp3/cp3SummaryClosing.png'),
	// ── Year 12 generated images (Modules 5–8) ────────────────────────────
	ammoniaBreaksArrhenius: staticFile('assets/hscscience/generated/lesson-1-acid-base-models/ammoniaBreaksArrhenius.png'),
	aspirinIbuprofenKa: staticFile('assets/hscscience/generated/lesson-9-ka-kb-ice/aspirinIbuprofenKa.png'),
	bakingSodaDualRole: staticFile('assets/hscscience/generated/lesson-7-conjugate-amphiprotic/bakingSodaDualRole.png'),
	bufferBloodBeakers: staticFile('assets/hscscience/generated/lesson-13-buffers/bufferBloodBeakers.png'),
	colaEnamelKa: staticFile('assets/hscscience/generated/lesson-12-ka-pka/colaEnamelKa.png'),
	fourStudentResponses: staticFile('assets/hscscience/generated/lesson-6-strong-weak-mastery/fourStudentResponses.png'),
	fourStudentsCurve: staticFile('assets/hscscience/generated/lesson-17-titration-mastery/fourStudentsCurve.png'),
	glassElectrodeProbe: staticFile('assets/hscscience/generated/lesson-19-industrial-digital/glassElectrodeProbe.png'),
	indicatorColourReveal: staticFile('assets/hscscience/generated/lesson-2-nomenclature-indicators/indicatorColourReveal.png'),
	indicatorWrongChoice: staticFile('assets/hscscience/generated/lesson-15-indicators/indicatorWrongChoice.png'),
	londonSmogScrubber: staticFile('assets/hscscience/generated/lesson-4-neutralisation-industry/londonSmogScrubber.png'),
	m5L10HookIceMeasurement: staticFile('assets/hscscience/generated/m5L10HookIceMeasurement.png'),
	m5L11HookExamTrap: staticFile('assets/hscscience/generated/m5L11HookExamTrap.png'),
	m5L12HookReactionGps: staticFile('assets/hscscience/generated/m5L12HookReactionGps.png'),
	m5L13HookTemperatureKeq: staticFile('assets/hscscience/generated/m5L13HookTemperatureKeq.png'),
	m5L14HookKeqFamily: staticFile('assets/hscscience/generated/m5L14HookKeqFamily.png'),
	m5L15HookHotColdPacks: staticFile('assets/hscscience/generated/m5L15HookHotColdPacks.png'),
	m5L16HookPrecipitate: staticFile('assets/hscscience/generated/m5L16HookPrecipitate.png'),
	m5L17HookSaturatedSolution: staticFile('assets/hscscience/generated/m5L17HookSaturatedSolution.png'),
	m5L18HookWillItPrecipitate: staticFile('assets/hscscience/generated/m5L18HookWillItPrecipitate.png'),
	m5L1SparklingBottle: staticFile('assets/hscscience/generated/lesson-1-static-dynamic/m5L1SparklingBottle.png'),
	m5L2BurnVsHaber: staticFile('assets/hscscience/generated/lesson-2-reversibility-entropy/m5L2BurnVsHaber.png'),
	m5L3NitrogenDioxideTube: staticFile('assets/hscscience/generated/lesson-3-collision-theory/m5L3NitrogenDioxideTube.png'),
	m5L4ThreeStudents: staticFile('assets/hscscience/generated/lesson-4-analogies-misconceptions/m5L4ThreeStudents.png'),
	m5L5ThiocyanateColour: staticFile('assets/hscscience/generated/lesson-5-lcp-concentration-temperature/m5L5ThiocyanateColour.png'),
	m5L6GasSyringeCompression: staticFile('assets/hscscience/generated/lesson-6-lcp-pressure-volume/m5L6GasSyringeCompression.png'),
	m5L7AmmoniaPlant: staticFile('assets/hscscience/generated/lesson-7-industrial-applications/m5L7AmmoniaPlant.png'),
	m5L8ExamScript: staticFile('assets/hscscience/generated/lesson-8-lcp-mastery/m5L8ExamScript.png'),
	m5L9AtmosphereStable: staticFile('assets/hscscience/generated/lesson-9-keq-expressions/m5L9AtmosphereStable.png'),
	neutralisationHeatBenchmark: staticFile('assets/hscscience/generated/lesson-3-enthalpy-neutralisation/neutralisationHeatBenchmark.png'),
	phScaleLogarithmic: staticFile('assets/hscscience/generated/lesson-8-ph-poh-strong/phScaleLogarithmic.png'),
	strongWeakBeakers: staticFile('assets/hscscience/generated/lesson-5-strong-vs-weak/strongWeakBeakers.png'),
	strongWeakEnthalpyThermometers: staticFile('assets/hscscience/generated/lesson-10-enthalpy-strong-weak/strongWeakEnthalpyThermometers.png'),
	titrationBenchSetup: staticFile('assets/hscscience/generated/lesson-14-titration-technique/titrationBenchSetup.png'),
	// ── Year 12 generated images (Modules 5–8) ────────────────────────────
	m7L10RefluxApparatus: staticFile('assets/hscscience/generated/m7-l10-reflux-apparatus.png'),
	m7L11Calorimeter: staticFile('assets/hscscience/generated/m7-l11-calorimeter.png'),
	m7L1HydrocarbonFamilies: staticFile('assets/hscscience/generated/m7-l1-hydrocarbon-families.png'),
	m7L2FunctionalGroups: staticFile('assets/hscscience/generated/m7-l2-functional-groups.png'),
	m7L3BranchingSurfaceArea: staticFile('assets/hscscience/generated/m7-l3-branching-surface-area.png'),
	m7L4SigmaPiBond: staticFile('assets/hscscience/generated/m7-l4-sigma-pi-bond.png'),
	m7L5BromineWaterTest: staticFile('assets/hscscience/generated/m7-l5-bromine-water-test.png'),
	m7L6Markovnikov: staticFile('assets/hscscience/generated/m7-l6-markovnikov.png'),
	m7L7AlkyneHydration: staticFile('assets/hscscience/generated/m7-l7-alkyne-hydration.png'),
	m7L9HydrogenBonding: staticFile('assets/hscscience/generated/m7-l9-hydrogen-bonding.png'),
	m7l13CarbonylComparison: staticFile('assets/hscscience/chem-y12-m7/l13/carbonyl-comparison.png'),
	m7l13HookVanillaRaspberry: staticFile('assets/hscscience/chem-y12-m7/l13/hook-vanilla-raspberry.png'),
	m7l14EthanoicAcidDimer: staticFile('assets/hscscience/chem-y12-m7/l14/ethanoic-acid-dimer.png'),
	m7l14HookWineVinegar: staticFile('assets/hscscience/chem-y12-m7/l14/hook-wine-vinegar.png'),
	m7l15EsterLinkage: staticFile('assets/hscscience/chem-y12-m7/l15/ester-linkage.png'),
	m7l15HookFruitEsters: staticFile('assets/hscscience/chem-y12-m7/l15/hook-fruit-esters.png'),
	m7l16AmineVsAmide: staticFile('assets/hscscience/chem-y12-m7/l16/amine-vs-amide.png'),
	m7l16HookAmines: staticFile('assets/hscscience/chem-y12-m7/l16/hook-amines.png'),
	m7l17HookGreaseWater: staticFile('assets/hscscience/chem-y12-m7/l17/hook-grease-water.png'),
	m7l17Micelle: staticFile('assets/hscscience/chem-y12-m7/l17/micelle.png'),
	m7l18ConjugateBaseStability: staticFile('assets/hscscience/chem-y12-m7/l18/conjugate-base-stability.png'),
	m7l18HookUnknownSolutions: staticFile('assets/hscscience/chem-y12-m7/l18/hook-unknown-solutions.png'),
	m7l19HookSynthesisRoute: staticFile('assets/hscscience/chem-y12-m7/l19/hook-synthesis-route.png'),
	m7l19ReactionMap: staticFile('assets/hscscience/chem-y12-m7/l19/reaction-map.png'),
	m7l20HookExamPathway: staticFile('assets/hscscience/chem-y12-m7/l20/hook-exam-pathway.png'),
	m7l20ReactionMap: staticFile('assets/hscscience/chem-y12-m7/l20/reaction-map.png'),
	m7l21AdditionMechanism: staticFile('assets/hscscience/chem-y12-m7/l21/addition-mechanism.png'),
	m7l21HookPolyethylene: staticFile('assets/hscscience/chem-y12-m7/l21/hook-polyethylene.png'),
	m7l22HookPolyester: staticFile('assets/hscscience/chem-y12-m7/l22/hook-polyester.png'),
	m7l22PetFormation: staticFile('assets/hscscience/chem-y12-m7/l22/pet-formation.png'),
	m7l23ChainArchitectures: staticFile('assets/hscscience/chem-y12-m7/l23/chain-architectures.png'),
	m7l23HookPolymerUses: staticFile('assets/hscscience/chem-y12-m7/l23/hook-polymer-uses.png'),
	// ── M8 L9–16 hook images (paths assigned by maintainer) ────────────────
	eutrophicationLake: staticFile('assets/hscscience/generated/m8-l9-eutrophication-lake.png'),
	waterTreatmentPlant: staticFile('assets/hscscience/generated/m8-l10-water-treatment-plant.png'),
	aspirinMolecule: staticFile('assets/hscscience/generated/m8-l11-aspirin-molecule.png'),
	entericCoatedTablet: staticFile('assets/hscscience/generated/m8-l12-enteric-coated-tablet.png'),
	thalidomideStory: staticFile('assets/hscscience/generated/m8-l13-thalidomide-story.png'),
	transdermalPatch: staticFile('assets/hscscience/generated/m8-l14-transdermal-patch.png'),
	aspirinSynthesisFlask: staticFile('assets/hscscience/generated/m8-l15-aspirin-synthesis-flask.png'),
	kevlarVsPolyethylene: staticFile('assets/hscscience/generated/m8-l16-kevlar-vs-polyethylene.png'),
	// ── Biology Year 12 generated images (Modules 5–8) ─────────────────────
	bioM5L10TranscriptionBubble: staticFile('assets/hscscience/generated/bio-y12-m5/transcription-bubble.png'),
	bioM5L11Streptomycin: staticFile('assets/hscscience/generated/bio-y12-m5/streptomycin-ribosome.png'),
	bioM5L12SickleCell: staticFile('assets/hscscience/generated/bio-y12-m5/sickle-cell-haemoglobin.png'),
	bioM5L13GalapagosFinches: staticFile('assets/hscscience/generated/bio-y12-m5/galapagos-finch-beaks.png'),
	bioM5L14PedigreeChart: staticFile('assets/hscscience/generated/bio-y12-m5/pedigree-chart.png'),
	bioM5L15BloodGroups: staticFile('assets/hscscience/generated/bio-y12-m5/abo-blood-antigens.png'),
	bioM5L16SnpComparison: staticFile('assets/hscscience/generated/bio-y12-m5/snp-base-comparison.png'),
	bioM5L17DnaProfile: staticFile('assets/hscscience/generated/bio-y12-m5/dna-profile-bands.png'),
	bioM5L18PopulationGenetics: staticFile('assets/hscscience/generated/bio-y12-m5/population-genetics-bottleneck.png'),
	bioM5L19GeneticPrivacy: staticFile('assets/hscscience/generated/bio-y12-m5/genetic-data-privacy.png'),
	bioM5L1BananaClone: staticFile('assets/hscscience/generated/bio-y12-m5/banana-clone-vulnerability.png'),
	bioM5L2SalmonSpawning: staticFile('assets/hscscience/generated/bio-y12-m5/salmon-external-fertilisation.png'),
	bioM5L3KomodoParthenogenesis: staticFile('assets/hscscience/generated/bio-y12-m5/komodo-parthenogenesis.png'),
	bioM5L4IvfEmbryo: staticFile('assets/hscscience/generated/bio-y12-m5/early-embryo-cleavage.png'),
	bioM5L5DollyCloning: staticFile('assets/hscscience/generated/bio-y12-m5/somatic-cell-nuclear-transfer.png'),
	bioM5L6DoubleHelix: staticFile('assets/hscscience/generated/bio-y12-m5/dna-double-helix.png'),
	bioM5L7HelaCells: staticFile('assets/hscscience/generated/bio-y12-m5/dividing-cells-mitosis.png'),
	bioM5L8NondisjunctionKaryotype: staticFile('assets/hscscience/generated/bio-y12-m5/chromosome-separation-meiosis.png'),
	bioM5L9PlasmidTransformation: staticFile('assets/hscscience/generated/bio-y12-m5/circular-dna-plasmids.png'),
	bioM6L10Crispr: staticFile('assets/hscscience/generated/bio-y12-m6/crispr-targeted-editing.png'),
	bioM6L11FrozenZooRhino: staticFile('assets/hscscience/generated/bio-y12-m6/frozen-zoo-rhino-biodiversity.png'),
	bioM6L12GeneDriveMosquito: staticFile('assets/hscscience/generated/bio-y12-m6/gene-drive-mosquito-spread.png'),
	bioM6L13TechnologyMap: staticFile('assets/hscscience/generated/bio-y12-m6/embryo-transfer-elite-cow.png'),
	bioM6L14ReproTechCompare: staticFile('assets/hscscience/generated/bio-y12-m6/artificial-insemination-pollination.png'),
	bioM6L15CloningDolly: staticFile('assets/hscscience/generated/bio-y12-m6/whole-organism-cloning-sheep.png'),
	bioM6L16RecombinantInsulin: staticFile('assets/hscscience/generated/bio-y12-m6/recombinant-insulin-bacteria.png'),
	bioM6L17BenefitsDomains: staticFile('assets/hscscience/generated/bio-y12-m6/genetic-technology-three-domains.png'),
	bioM6L18LongTermChange: staticFile('assets/hscscience/generated/bio-y12-m6/green-revolution-benefit-cost.png'),
	bioM6L19FinchVariation: staticFile('assets/hscscience/generated/bio-y12-m6/finch-variation-allele-frequency.png'),
	bioM6L1Superbug: staticFile('assets/hscscience/generated/bio-y12-m6/superbug-pre-existing-resistance.png'),
	bioM6L2RadiationDna: staticFile('assets/hscscience/generated/bio-y12-m6/radiation-dna-damage-risk.png'),
	bioM6L3SickleCell: staticFile('assets/hscscience/generated/bio-y12-m6/sickle-cell-red-blood-cells.png'),
	bioM6L4ChromosomeTypes: staticFile('assets/hscscience/generated/bio-y12-m6/chromosomal-mutation-types.png'),
	bioM6L5SomaticGermline: staticFile('assets/hscscience/generated/bio-y12-m6/somatic-vs-germline-body.png'),
	bioM6L6FinchBeaks: staticFile('assets/hscscience/generated/bio-y12-m6/finch-beak-variation.png'),
	bioM6L7Cichlids: staticFile('assets/hscscience/generated/bio-y12-m6/cichlid-divergence-isolation.png'),
	bioM6L8FermentationScope: staticFile('assets/hscscience/generated/bio-y12-m6/fermentation-traditional-modern.png'),
	bioM6L9GoldenRice: staticFile('assets/hscscience/generated/bio-y12-m6/golden-rice-stakeholders.png'),
	bioM7L10Phagocytosis: staticFile('assets/hscscience/generated/bio-y12-m7/phagocyte-engulfing-pathogen.png'),
	bioM7L11AntibodyStructure: staticFile('assets/hscscience/generated/bio-y12-m7/antibody-binding-antigen.png'),
	bioM7L12HivTHelper: staticFile('assets/hscscience/generated/bio-y12-m7/hiv-t-helper.png'),
	bioM7L13JennerMemory: staticFile('assets/hscscience/generated/bio-y12-m7/jenner-memory.png'),
	bioM7L14PolioDecline: staticFile('assets/hscscience/generated/bio-y12-m7/vaccine-protection.png'),
	bioM7L15SemmelweisWards: staticFile('assets/hscscience/generated/bio-y12-m7/semmelweis-handwashing.png'),
	bioM7L16PenicillinResistance: staticFile('assets/hscscience/generated/bio-y12-m7/penicillin-resistance.png'),
	bioM7L17SterileInsect: staticFile('assets/hscscience/generated/bio-y12-m7/sterile-insect.png'),
	bioM7L18MalariaBurden: staticFile('assets/hscscience/generated/bio-y12-m7/mosquito-vector.png'),
	bioM7L19VeniceQuarantine: staticFile('assets/hscscience/generated/bio-y12-m7/venice-quarantine.png'),
	bioM7L1PandemicWorld: staticFile('assets/hscscience/generated/bio-y12-m7/pandemic-spread-across-globe.png'),
	bioM7L20BushMedicineIP: staticFile('assets/hscscience/generated/bio-y12-m7/bush-medicine.png'),
	bioM7L21PandemicStrategies: staticFile('assets/hscscience/generated/bio-y12-m7/one-health-globe.png'),
	bioM7L2PenicillinZone: staticFile('assets/hscscience/generated/bio-y12-m7/penicillin-zone-of-inhibition.png'),
	bioM7L3SwanNeckFlask: staticFile('assets/hscscience/generated/bio-y12-m7/pasteur-swan-neck-flask.png'),
	bioM7L4SnowCholeraMap: staticFile('assets/hscscience/generated/bio-y12-m7/snow-cholera-pump-map.png'),
	bioM7L5AgarColonies: staticFile('assets/hscscience/generated/bio-y12-m7/agar-plate-colony-count.png'),
	bioM7L6MyrtleRust: staticFile('assets/hscscience/generated/bio-y12-m7/myrtle-rust-on-leaves.png'),
	bioM7L7CattleBiosecurity: staticFile('assets/hscscience/generated/bio-y12-m7/livestock-biosecurity-barrier.png'),
	bioM7L8PlantDefenceCrossSection: staticFile('assets/hscscience/generated/bio-y12-m7/plant-defence-cross-section.png'),
	bioM7L9Inflammation: staticFile('assets/hscscience/generated/bio-y12-m7/inflammation-skin-response.png'),
	bioM8L10CellDivision: staticFile('assets/hscscience/generated/bio-y12-m8/cell-division.png'),
	bioM8L11DiagnosisCases: staticFile('assets/hscscience/generated/bio-y12-m8/diagnosis-cases.png'),
	bioM8L12EpidemiologyStudy: staticFile('assets/hscscience/generated/bio-y12-m8/epidemiology-study.png'),
	bioM8L13RiskFraming: staticFile('assets/hscscience/generated/bio-y12-m8/risk-framing.png'),
	bioM8L14CheckpointInhibitor: staticFile('assets/hscscience/generated/bio-y12-m8/checkpoint-inhibitor.png'),
	bioM8L15TreatmentEquity: staticFile('assets/hscscience/generated/bio-y12-m8/treatment-equity.png'),
	bioM8L16SelfTolerance: staticFile('assets/hscscience/generated/bio-y12-m8/self-tolerance.png'),
	bioM8L17Karyotype: staticFile('assets/hscscience/generated/bio-y12-m8/karyotype.png'),
	bioM8L18CochlearImplant: staticFile('assets/hscscience/generated/bio-y12-m8/cochlear-implant.png'),
	bioM8L19MyopiaFocus: staticFile('assets/hscscience/generated/bio-y12-m8/myopia-focus.png'),
	bioM8L1GlucoseStability: staticFile('assets/hscscience/generated/bio-y12-m8/glucose-stability.png'),
	bioM8L20DialysisMachine: staticFile('assets/hscscience/generated/bio-y12-m8/dialysis-machine.png'),
	bioM8L21IntegratedCare: staticFile('assets/hscscience/generated/bio-y12-m8/integrated-care.png'),
	bioM8L2HeatwaveTwoAnimals: staticFile('assets/hscscience/generated/bio-y12-m8/heatwave-two-animals.png'),
	bioM8L3RunnerGlucose: staticFile('assets/hscscience/generated/bio-y12-m8/runner-glucose.png'),
	bioM8L4DesertHydration: staticFile('assets/hscscience/generated/bio-y12-m8/desert-hydration.png'),
	bioM8L5DesertPlant: staticFile('assets/hscscience/generated/bio-y12-m8/desert-plant.png'),
	bioM8L6CausesOfDeathShift: staticFile('assets/hscscience/generated/bio-y12-m8/causes-of-death-shift.png'),
	bioM8L7GenePathway: staticFile('assets/hscscience/generated/bio-y12-m8/gene-pathway.png'),
	bioM8L8TobaccoExposure: staticFile('assets/hscscience/generated/bio-y12-m8/tobacco-exposure.png'),
	bioM8L9NutritionBalance: staticFile('assets/hscscience/generated/bio-y12-m8/nutrition-balance.png'),
} as const;

export type AssetName = keyof typeof ASSETS;
