import type {DiagramConfig} from '../../lesson/types';
import {BridgeDiagram} from './BridgeDiagram';
import {DozenMoleDiagram} from './DozenMoleDiagram';
import {MassComparisonDiagram} from './MassComparisonDiagram';
import {BalanceDiagram} from './BalanceDiagram';
import {DataChart} from '../../animations/DiagramPrimitives';
import {VennDiagram} from './VennDiagram';
import {FlowDiagram} from './FlowDiagram';
import {OrbitDiagram} from './OrbitDiagram';
import {TableReveal} from './TableReveal';
import {BeforeAfterDiagram} from './BeforeAfterDiagram';
import {ExplodeDiagram} from './ExplodeDiagram';
import {GalvanicCellDiagram} from './GalvanicCellDiagram';
import {EnergyProfileDiagram} from './EnergyProfileDiagram';
import {BoltzmannDistributionDiagram} from './BoltzmannDistributionDiagram';
import {GasVolumeComparisonDiagram} from './GasVolumeComparisonDiagram';
import {MassBreakdownDiagram} from './MassBreakdownDiagram';
import {ConcentrationCompareDiagram} from './ConcentrationCompareDiagram';
import {TitrationSetupDiagram} from './TitrationSetupDiagram';
import {LimitingExcessDiagram} from './LimitingExcessDiagram';
import {ErrorDartboardDiagram} from './ErrorDartboardDiagram';
import {CalorimeterDiagram} from './CalorimeterDiagram';
import {BondEnergyDiagram} from './BondEnergyDiagram';
import {HessCycleDiagram} from './HessCycleDiagram';
import {EntropyDisorderDiagram} from './EntropyDisorderDiagram';
import {GibbsSpontaneityDiagram} from './GibbsSpontaneityDiagram';
import {ReductionPotentialLadderDiagram} from './ReductionPotentialLadderDiagram';
import {IsotopeAtomsDiagram} from './IsotopeAtomsDiagram';
import {AufbauStaircaseDiagram} from './AufbauStaircaseDiagram';
import {LatticeVsElectronSeaDiagram} from './LatticeVsElectronSeaDiagram';
import {LineGraphDiagram} from './LineGraphDiagram';
import {PunnettSquareDiagram} from './PunnettSquareDiagram';
import {PedigreeChartDiagram} from './PedigreeChartDiagram';
import {DnaHelixDiagram} from './DnaHelixDiagram';
import {TranscriptionStrandDiagram} from './TranscriptionStrandDiagram';
import {ChromosomeMutationDiagram} from './ChromosomeMutationDiagram';
import {LottieDiagram} from './LottieDiagram';
import {Molecule3DDiagram} from './Molecule3DDiagram';
import {Circuit3DDiagram} from './Circuit3DDiagram';

export const DiagramRenderer = ({diagram}: {diagram: DiagramConfig}) => {
	switch (diagram.type) {
		case 'bridge':         return <BridgeDiagram />;
		case 'dozenMole':      return <DozenMoleDiagram />;
		case 'massComparison': return <MassComparisonDiagram />;
		case 'balance':        return <BalanceDiagram {...diagram} />;
		case 'barChart':       return <DataChart kind="bar" data={diagram.bars} delay={diagram.delay ?? 0} />;
		case 'venn':           return <VennDiagram {...diagram} />;
		case 'flow':           return <FlowDiagram {...diagram} />;
		case 'orbit':          return <OrbitDiagram {...diagram} />;
		case 'table':          return <TableReveal {...diagram} />;
		case 'beforeAfter':    return <BeforeAfterDiagram {...diagram} />;
		case 'explode':        return <ExplodeDiagram {...diagram} />;
		case 'galvanicCell':   return <GalvanicCellDiagram {...diagram} />;
		case 'energyProfile':  return <EnergyProfileDiagram {...diagram} />;
		case 'boltzmannDistribution': return <BoltzmannDistributionDiagram {...diagram} />;
		case 'gasVolumeComparison': return <GasVolumeComparisonDiagram />;
		case 'massBreakdown':  return <MassBreakdownDiagram segments={diagram.segments} />;
		case 'concentrationCompare': return <ConcentrationCompareDiagram />;
		case 'titrationSetup': return <TitrationSetupDiagram />;
		case 'limitingExcess': return <LimitingExcessDiagram />;
		case 'errorDartboard': return <ErrorDartboardDiagram />;
		case 'calorimeter':    return <CalorimeterDiagram />;
		case 'bondEnergy':     return <BondEnergyDiagram />;
		case 'hessCycle':      return <HessCycleDiagram />;
		case 'entropyDisorder': return <EntropyDisorderDiagram />;
		case 'gibbsSpontaneity': return <GibbsSpontaneityDiagram />;
		case 'reductionPotentialLadder': return <ReductionPotentialLadderDiagram />;
		case 'isotopeAtoms':   return <IsotopeAtomsDiagram />;
		case 'aufbauStaircase': return <AufbauStaircaseDiagram />;
		case 'latticeVsElectronSea': return <LatticeVsElectronSeaDiagram />;
		case 'lineGraph':      return <LineGraphDiagram {...diagram} />;
		case 'punnettSquare':  return <PunnettSquareDiagram top={diagram.top} left={diagram.left} />;
		case 'pedigree':       return <PedigreeChartDiagram />;
		case 'dnaHelix':       return <DnaHelixDiagram />;
		case 'transcriptionStrand': return <TranscriptionStrandDiagram />;
		case 'chromosomeMutation': return <ChromosomeMutationDiagram />;
		case 'lottie':         return <LottieDiagram src={diagram.src} loop={diagram.loop} speed={diagram.speed} />;
		case 'molecule3d':     return <Molecule3DDiagram {...diagram} />;
		case 'circuit3d':      return <Circuit3DDiagram {...diagram} />;
		default:               return null;
	}
};
