// Auto-generated by scripts/generate-lesson-registry.mjs. Do not edit by hand.
import type {LessonData} from '../lesson/types';
import lesson1Data from './biology-y12-m5-l1-reproduction-continuity.json';
import lesson2Data from './biology-y12-m5-l10-transcription-dna-to-mrna.json';
import lesson3Data from './biology-y12-m5-l11-translation.json';
import lesson4Data from './biology-y12-m5-l12-proteins-phenotype.json';
import lesson5Data from './biology-y12-m5-l13-sources-genetic-variation.json';
import lesson6Data from './biology-y12-m5-l14-mendelian-patterns.json';
import lesson7Data from './biology-y12-m5-l15-non-mendelian-patterns.json';
import lesson8Data from './biology-y12-m5-l16-frequency-data-snp-analysis.json';
import lesson9Data from './biology-y12-m5-l17-dna-sequencing-profiling.json';
import lesson10Data from './biology-y12-m5-l18-large-scale-population-genetics.json';
import lesson11Data from './biology-y12-m5-l19-predicting-population-genetic-patterns.json';
import lesson12Data from './biology-y12-m5-l2-reproduction-in-animals.json';
import lesson13Data from './biology-y12-m5-l3-reproduction-plants-fungi-bacteria-protists.json';
import lesson14Data from './biology-y12-m5-l4-mammalian-reproduction.json';
import lesson15Data from './biology-y12-m5-l5-manipulating-reproduction-agriculture.json';
import lesson16Data from './biology-y12-m5-l6-dna-structure-replication.json';
import lesson17Data from './biology-y12-m5-l7-mitosis.json';
import lesson18Data from './biology-y12-m5-l8-meiosis.json';
import lesson19Data from './biology-y12-m5-l9-dna-prokaryotes-eukaryotes.json';
import lesson20Data from './biology-y12-m6-l1-mutation-alleles-genetic-change.json';
import lesson21Data from './biology-y12-m6-l10-future-directions-benefits.json';
import lesson22Data from './biology-y12-m6-l11-biodiversity-change-genetic-techniques.json';
import lesson23Data from './biology-y12-m6-l12-biotechnology-synthesis-evaluation.json';
import lesson24Data from './biology-y12-m6-l13-current-genetic-technologies.json';
import lesson25Data from './biology-y12-m6-l14-reproductive-technologies-ai-ap.json';
import lesson26Data from './biology-y12-m6-l15-cloning-whole-organism-gene.json';
import lesson27Data from './biology-y12-m6-l16-recombinant-dna-transgenic-organisms.json';
import lesson28Data from './biology-y12-m6-l17-benefits-genetic-technologies.json';
import lesson29Data from './biology-y12-m6-l18-long-term-population-change.json';
import lesson30Data from './biology-y12-m6-l19-variation-allele-frequency.json';
import lesson31Data from './biology-y12-m6-l2-mutagens.json';
import lesson32Data from './biology-y12-m6-l3-point-mutation.json';
import lesson33Data from './biology-y12-m6-l4-chromosomal-mutation.json';
import lesson34Data from './biology-y12-m6-l5-somatic-germline-coding-noncoding.json';
import lesson35Data from './biology-y12-m6-l6-causes-of-genetic-variation.json';
import lesson36Data from './biology-y12-m6-l7-gene-pools.json';
import lesson37Data from './biology-y12-m6-l8-biotechnology-definitions.json';
import lesson38Data from './biology-y12-m6-l9-ethics-social-implications.json';
import lesson39Data from './biology-y12-m7-l1-what-is-infectious-disease.json';
import lesson40Data from './biology-y12-m7-l10-innate-immune-system.json';
import lesson41Data from './biology-y12-m7-l11-adaptive-immunity-antigens-antibodies.json';
import lesson42Data from './biology-y12-m7-l12-t-cells-cell-mediated-immunity.json';
import lesson43Data from './biology-y12-m7-l13-primary-secondary-immune-response.json';
import lesson44Data from './biology-y12-m7-l14-vaccination-active-passive-immunity.json';
import lesson45Data from './biology-y12-m7-l15-hygiene-quarantine-public-health.json';
import lesson46Data from './biology-y12-m7-l16-antibiotics-and-antivirals.json';
import lesson47Data from './biology-y12-m7-l17-pesticides-and-genetic-engineering.json';
import lesson48Data from './biology-y12-m7-l18-malaria-and-dengue-global-case-study.json';
import lesson49Data from './biology-y12-m7-l19-historical-cultural-disease-control.json';
import lesson50Data from './biology-y12-m7-l2-classifying-pathogens.json';
import lesson51Data from './biology-y12-m7-l20-indigenous-protocols-bush-medicine.json';
import lesson52Data from './biology-y12-m7-l21-environmental-management-pandemic-control.json';
import lesson53Data from './biology-y12-m7-l3-koch-pasteur-germ-theory.json';
import lesson54Data from './biology-y12-m7-l4-modes-of-transmission.json';
import lesson55Data from './biology-y12-m7-l5-microbial-testing.json';
import lesson56Data from './biology-y12-m7-l6-disease-in-agriculture-plants.json';
import lesson57Data from './biology-y12-m7-l7-disease-in-agriculture-animals.json';
import lesson58Data from './biology-y12-m7-l8-plant-responses-to-pathogens.json';
import lesson59Data from './biology-y12-m7-l9-physical-chemical-responses-animals.json';
import lesson60Data from './biology-y12-m8-l1-homeostasis-feedback-loops.json';
import lesson61Data from './biology-y12-m8-l10-cancer.json';
import lesson62Data from './biology-y12-m8-l11-causes-mastery.json';
import lesson63Data from './biology-y12-m8-l12-epidemiology-measures-study-design.json';
import lesson64Data from './biology-y12-m8-l13a-analysing-epidemiological-data.json';
import lesson65Data from './biology-y12-m8-l13b-analysing-epidemiological-data.json';
import lesson66Data from './biology-y12-m8-l14-treatment-non-infectious-disease.json';
import lesson67Data from './biology-y12-m8-l15-treatment-management-evaluation.json';
import lesson68Data from './biology-y12-m8-l16-autoimmune-diseases-allergies.json';
import lesson69Data from './biology-y12-m8-l17a-genetic-disorders-inheritance.json';
import lesson70Data from './biology-y12-m8-l17b-genetic-disorders-applying.json';
import lesson71Data from './biology-y12-m8-l18a-hearing-loss-foundations.json';
import lesson72Data from './biology-y12-m8-l18b-cochlear-implants-applying.json';
import lesson73Data from './biology-y12-m8-l19a-visual-disorders-eye-and-errors.json';
import lesson74Data from './biology-y12-m8-l19b-visual-disorders-technologies.json';
import lesson75Data from './biology-y12-m8-l2-temperature-regulation.json';
import lesson76Data from './biology-y12-m8-l20-kidney-disorders-dialysis-transplantation.json';
import lesson77Data from './biology-y12-m8-l21-module-8-mastery-integration.json';
import lesson78Data from './biology-y12-m8-l3-glucose-regulation.json';
import lesson79Data from './biology-y12-m8-l4-water-balance.json';
import lesson80Data from './biology-y12-m8-l5-plant-water-balance.json';
import lesson81Data from './biology-y12-m8-l6-causes-noninfectious-disease.json';
import lesson82Data from './biology-y12-m8-l7-genetic-diseases.json';
import lesson83Data from './biology-y12-m8-l8-environmental-diseases.json';
import lesson84Data from './biology-y12-m8-l9-nutritional-diseases.json';
import lesson85Data from './chemistry-y11-m1-l1-properties-classification.json';
import lesson86Data from './chemistry-y11-m1-l10-intermolecular-forces.json';
import lesson87Data from './chemistry-y11-m1-l11-polymers-structure-properties.json';
import lesson88Data from './chemistry-y11-m1-l12-solubility-like-dissolves-like.json';
import lesson89Data from './chemistry-y11-m1-l13-atomic-models-historical.json';
import lesson90Data from './chemistry-y11-m1-l14-isotopes-relative-atomic-mass.json';
import lesson91Data from './chemistry-y11-m1-l15-periodic-table-organisation.json';
import lesson92Data from './chemistry-y11-m1-l16-electron-configuration-subshells.json';
import lesson93Data from './chemistry-y11-m1-l17-periodic-trends-atomic-radius.json';
import lesson94Data from './chemistry-y11-m1-l18-electronegativity-reactivity.json';
import lesson95Data from './chemistry-y11-m1-l19-electron-configuration-behaviour.json';
import lesson96Data from './chemistry-y11-m1-l2-properties-elements-compounds-mixtures.json';
import lesson97Data from './chemistry-y11-m1-l20-module-synthesis-review.json';
import lesson98Data from './chemistry-y11-m1-l3-separation-physical-methods.json';
import lesson99Data from './chemistry-y11-m1-l4-separation-advanced-methods.json';
import lesson100Data from './chemistry-y11-m1-l5-iq1-consolidation.json';
import lesson101Data from './chemistry-y11-m1-l6-chemical-bonding-overview.json';
import lesson102Data from './chemistry-y11-m1-l7-ionic-bonding-properties.json';
import lesson103Data from './chemistry-y11-m1-l8-metallic-bonding-properties.json';
import lesson104Data from './chemistry-y11-m1-l9-covalent-molecular-network.json';
import lesson105Data from './chemistry-y11-m2-l1-mole-concept.json';
import lesson106Data from './chemistry-y11-m2-l10-volumetric-analysis-titration.json';
import lesson107Data from './chemistry-y11-m2-l11-stoichiometry-mole-ratios.json';
import lesson108Data from './chemistry-y11-m2-l12-mass-mass-stoichiometry.json';
import lesson109Data from './chemistry-y11-m2-l13-limiting-reagents.json';
import lesson110Data from './chemistry-y11-m2-l14-percentage-yield-purity.json';
import lesson111Data from './chemistry-y11-m2-l15-gas-stoichiometry.json';
import lesson112Data from './chemistry-y11-m2-l16-stoichiometry-in-solution.json';
import lesson113Data from './chemistry-y11-m2-l17-back-calculations.json';
import lesson114Data from './chemistry-y11-m2-l18-working-scientifically.json';
import lesson115Data from './chemistry-y11-m2-l19-synthesis-exam-practice.json';
import lesson116Data from './chemistry-y11-m2-l1a-mole-understanding.json';
import lesson117Data from './chemistry-y11-m2-l1b-mole-applying.json';
import lesson118Data from './chemistry-y11-m2-l2-molar-mass.json';
import lesson119Data from './chemistry-y11-m2-l20-module-review.json';
import lesson120Data from './chemistry-y11-m2-l3-empirical-molecular-formulas.json';
import lesson121Data from './chemistry-y11-m2-l4-gases-molar-volume.json';
import lesson122Data from './chemistry-y11-m2-l5-mole-consolidation.json';
import lesson123Data from './chemistry-y11-m2-l6-concentration.json';
import lesson124Data from './chemistry-y11-m2-l7-standard-solutions-dilutions.json';
import lesson125Data from './chemistry-y11-m2-l8-concentration-in-context.json';
import lesson126Data from './chemistry-y11-m2-l9-gravimetric-analysis.json';
import lesson127Data from './chemistry-y11-m3-cp1-predicting-products.json';
import lesson128Data from './chemistry-y11-m3-cp2-metal-reactivity.json';
import lesson129Data from './chemistry-y11-m3-cp3-rates-synthesis.json';
import lesson130Data from './chemistry-y11-m3-l1-physical-chemical-change.json';
import lesson131Data from './chemistry-y11-m3-l10-inert-electrodes.json';
import lesson132Data from './chemistry-y11-m3-l11-collision-theory.json';
import lesson133Data from './chemistry-y11-m3-l12-factors-affecting-rate.json';
import lesson134Data from './chemistry-y11-m3-l2-synthesis-decomposition.json';
import lesson135Data from './chemistry-y11-m3-l3-precipitation-solubility.json';
import lesson136Data from './chemistry-y11-m3-l4-combustion-reactions.json';
import lesson137Data from './chemistry-y11-m3-l5-acid-base-acid-carbonate.json';
import lesson138Data from './chemistry-y11-m3-l6-indigenous-detoxification.json';
import lesson139Data from './chemistry-y11-m3-l7-metal-activity-series.json';
import lesson140Data from './chemistry-y11-m3-l8-redox-oxidation-states.json';
import lesson141Data from './chemistry-y11-m3-l9-galvanic-cells.json';
import lesson142Data from './chemistry-y11-m4-cp1-energy-changes.json';
import lesson143Data from './chemistry-y11-m4-cp2-enthalpy-hess.json';
import lesson144Data from './chemistry-y11-m4-cp3-entropy-gibbs.json';
import lesson145Data from './chemistry-y11-m4-l1-enthalpy-energy-profiles.json';
import lesson146Data from './chemistry-y11-m4-l10-hess-combustion-consolidation.json';
import lesson147Data from './chemistry-y11-m4-l11-entropy.json';
import lesson148Data from './chemistry-y11-m4-l12-calculating-entropy.json';
import lesson149Data from './chemistry-y11-m4-l13-gibbs-free-energy.json';
import lesson150Data from './chemistry-y11-m4-l2-calorimetry-combustion.json';
import lesson151Data from './chemistry-y11-m4-l3-calorimetry-neutralisation.json';
import lesson152Data from './chemistry-y11-m4-l4-calorimetry-dissolution.json';
import lesson153Data from './chemistry-y11-m4-l5-activation-energy-catalysts.json';
import lesson154Data from './chemistry-y11-m4-l6-bond-energy.json';
import lesson155Data from './chemistry-y11-m4-l7-enthalpy-of-formation.json';
import lesson156Data from './chemistry-y11-m4-l8-hesss-law.json';
import lesson157Data from './chemistry-y11-m4-l9-hess-photosynthesis-respiration.json';
import lesson158Data from './chemistry-y12-m5-l1-static-dynamic-equilibrium.json';
import lesson159Data from './chemistry-y12-m5-l10-calculating-keq-ice-tables.json';
import lesson160Data from './chemistry-y12-m5-l11-ice-table-mastery.json';
import lesson161Data from './chemistry-y12-m5-l12-reaction-quotient-q.json';
import lesson162Data from './chemistry-y12-m5-l13-temperature-keq-colourimetry.json';
import lesson163Data from './chemistry-y12-m5-l14-ka-kb-gibbs.json';
import lesson164Data from './chemistry-y12-m5-l15-dissolution-atsi.json';
import lesson165Data from './chemistry-y12-m5-l16-solubility-rules-precipitation.json';
import lesson166Data from './chemistry-y12-m5-l17-solubility-product-ksp.json';
import lesson167Data from './chemistry-y12-m5-l18-qsp-common-ion-effect.json';
import lesson168Data from './chemistry-y12-m5-l2-reversibility-entropy.json';
import lesson169Data from './chemistry-y12-m5-l3-collision-theory-equilibrium.json';
import lesson170Data from './chemistry-y12-m5-l4-equilibrium-analogies-misconceptions.json';
import lesson171Data from './chemistry-y12-m5-l5-lcp-concentration-temperature.json';
import lesson172Data from './chemistry-y12-m5-l6-lcp-pressure-volume-catalysts.json';
import lesson173Data from './chemistry-y12-m5-l7-industrial-applications-equilibrium.json';
import lesson174Data from './chemistry-y12-m5-l8-lcp-mastery-consolidation.json';
import lesson175Data from './chemistry-y12-m5-l9-writing-keq-expressions.json';
import lesson176Data from './chemistry-y12-m6-l1-acid-base-models.json';
import lesson177Data from './chemistry-y12-m6-l10-neutralisation-enthalpy-strong-vs-weak.json';
import lesson178Data from './chemistry-y12-m6-l11-ph-calculations-mastery.json';
import lesson179Data from './chemistry-y12-m6-l12-ka-pka-acid-strength.json';
import lesson180Data from './chemistry-y12-m6-l13-buffers.json';
import lesson181Data from './chemistry-y12-m6-l14-titration-technique.json';
import lesson182Data from './chemistry-y12-m6-l15-indicators.json';
import lesson183Data from './chemistry-y12-m6-l16-titration-curves.json';
import lesson184Data from './chemistry-y12-m6-l17-titration-indicator-mastery.json';
import lesson185Data from './chemistry-y12-m6-l18-back-conductometric-titration.json';
import lesson186Data from './chemistry-y12-m6-l19-industrial-digital-analysis.json';
import lesson187Data from './chemistry-y12-m6-l2-nomenclature-indicators-acid-reactions.json';
import lesson188Data from './chemistry-y12-m6-l3-enthalpy-of-neutralisation.json';
import lesson189Data from './chemistry-y12-m6-l4-neutralisation-everyday-industry.json';
import lesson190Data from './chemistry-y12-m6-l5-strong-vs-weak-acids-bases.json';
import lesson191Data from './chemistry-y12-m6-l6-strong-weak-mastery-salt-hydrolysis.json';
import lesson192Data from './chemistry-y12-m6-l7-conjugate-pairs-amphiprotic-water.json';
import lesson193Data from './chemistry-y12-m6-l8-ph-poh-strong-acids-bases.json';
import lesson194Data from './chemistry-y12-m6-l9-ka-kb-ice-tables.json';
import lesson195Data from './chemistry-y12-m7-l1-intro-iupac-nomenclature.json';
import lesson196Data from './chemistry-y12-m7-l10-alcohol-production.json';
import lesson197Data from './chemistry-y12-m7-l11-combustion-of-alcohols.json';
import lesson198Data from './chemistry-y12-m7-l12-alcohol-reactions.json';
import lesson199Data from './chemistry-y12-m7-l13-aldehydes-and-ketones.json';
import lesson200Data from './chemistry-y12-m7-l14-carboxylic-acids.json';
import lesson201Data from './chemistry-y12-m7-l15-esters.json';
import lesson202Data from './chemistry-y12-m7-l16-amines-and-amides.json';
import lesson203Data from './chemistry-y12-m7-l17-soaps-and-detergents.json';
import lesson204Data from './chemistry-y12-m7-l18-organic-acids-and-bases.json';
import lesson205Data from './chemistry-y12-m7-l19-reaction-pathways.json';
import lesson206Data from './chemistry-y12-m7-l2-functional-groups-isomers.json';
import lesson207Data from './chemistry-y12-m7-l20-organic-reactions-mastery.json';
import lesson208Data from './chemistry-y12-m7-l21-addition-polymers.json';
import lesson209Data from './chemistry-y12-m7-l22-condensation-polymers.json';
import lesson210Data from './chemistry-y12-m7-l23-polymers-properties-and-environment.json';
import lesson211Data from './chemistry-y12-m7-l3-hydrocarbons-properties.json';
import lesson212Data from './chemistry-y12-m7-l4-structure-bonding.json';
import lesson213Data from './chemistry-y12-m7-l5-hydrocarbon-reactions.json';
import lesson214Data from './chemistry-y12-m7-l6-alkene-reactions.json';
import lesson215Data from './chemistry-y12-m7-l7-alkyne-alkane-reactions.json';
import lesson216Data from './chemistry-y12-m7-l8-reactions-mastery.json';
import lesson217Data from './chemistry-y12-m7-l9-alcohol-structure-properties.json';
import lesson218Data from './chemistry-y12-m8-l1-acid-base-titrations-indicators.json';
import lesson219Data from './chemistry-y12-m8-l10-water-treatment-processes.json';
import lesson220Data from './chemistry-y12-m8-l11-drug-classification-functional-groups.json';
import lesson221Data from './chemistry-y12-m8-l12-acid-base-properties-drug-molecules.json';
import lesson222Data from './chemistry-y12-m8-l13-optical-isomerism-chirality.json';
import lesson223Data from './chemistry-y12-m8-l14-solubility-polarity-drug-delivery.json';
import lesson224Data from './chemistry-y12-m8-l15-drug-synthesis-green-chemistry.json';
import lesson225Data from './chemistry-y12-m8-l16-polymers-structure-properties.json';
import lesson226Data from './chemistry-y12-m8-l2-gravimetric-analysis.json';
import lesson227Data from './chemistry-y12-m8-l3-precipitation-qualitative-analysis.json';
import lesson228Data from './chemistry-y12-m8-l4-spectroscopic-analysis-uv-vis-aas.json';
import lesson229Data from './chemistry-y12-m8-l5-chromatography-tlc-column-hplc.json';
import lesson230Data from './chemistry-y12-m8-l6-water-quality-parameters-standards.json';
import lesson231Data from './chemistry-y12-m8-l7-monitoring-dissolved-oxygen-bod.json';
import lesson232Data from './chemistry-y12-m8-l8-heavy-metal-contamination-analysis.json';
import lesson233Data from './chemistry-y12-m8-l9-nutrient-pollution-eutrophication.json';

export const lessons: {id: string; data: LessonData}[] = [
  {id: 'Biology-Y12-M5-L1', data: lesson1Data as LessonData},
  {id: 'Biology-Y12-M5-L10', data: lesson2Data as LessonData},
  {id: 'Biology-Y12-M5-L11', data: lesson3Data as LessonData},
  {id: 'Biology-Y12-M5-L12', data: lesson4Data as LessonData},
  {id: 'Biology-Y12-M5-L13', data: lesson5Data as LessonData},
  {id: 'Biology-Y12-M5-L14', data: lesson6Data as LessonData},
  {id: 'Biology-Y12-M5-L15', data: lesson7Data as LessonData},
  {id: 'Biology-Y12-M5-L16', data: lesson8Data as LessonData},
  {id: 'Biology-Y12-M5-L17', data: lesson9Data as LessonData},
  {id: 'Biology-Y12-M5-L18', data: lesson10Data as LessonData},
  {id: 'Biology-Y12-M5-L19', data: lesson11Data as LessonData},
  {id: 'Biology-Y12-M5-L2', data: lesson12Data as LessonData},
  {id: 'Biology-Y12-M5-L3', data: lesson13Data as LessonData},
  {id: 'Biology-Y12-M5-L4', data: lesson14Data as LessonData},
  {id: 'Biology-Y12-M5-L5', data: lesson15Data as LessonData},
  {id: 'Biology-Y12-M5-L6', data: lesson16Data as LessonData},
  {id: 'Biology-Y12-M5-L7', data: lesson17Data as LessonData},
  {id: 'Biology-Y12-M5-L8', data: lesson18Data as LessonData},
  {id: 'Biology-Y12-M5-L9', data: lesson19Data as LessonData},
  {id: 'Biology-Y12-M6-L1', data: lesson20Data as LessonData},
  {id: 'Biology-Y12-M6-L10', data: lesson21Data as LessonData},
  {id: 'Biology-Y12-M6-L11', data: lesson22Data as LessonData},
  {id: 'Biology-Y12-M6-L12', data: lesson23Data as LessonData},
  {id: 'Biology-Y12-M6-L13', data: lesson24Data as LessonData},
  {id: 'Biology-Y12-M6-L14', data: lesson25Data as LessonData},
  {id: 'Biology-Y12-M6-L15', data: lesson26Data as LessonData},
  {id: 'Biology-Y12-M6-L16', data: lesson27Data as LessonData},
  {id: 'Biology-Y12-M6-L17', data: lesson28Data as LessonData},
  {id: 'Biology-Y12-M6-L18', data: lesson29Data as LessonData},
  {id: 'Biology-Y12-M6-L19', data: lesson30Data as LessonData},
  {id: 'Biology-Y12-M6-L2', data: lesson31Data as LessonData},
  {id: 'Biology-Y12-M6-L3', data: lesson32Data as LessonData},
  {id: 'Biology-Y12-M6-L4', data: lesson33Data as LessonData},
  {id: 'Biology-Y12-M6-L5', data: lesson34Data as LessonData},
  {id: 'Biology-Y12-M6-L6', data: lesson35Data as LessonData},
  {id: 'Biology-Y12-M6-L7', data: lesson36Data as LessonData},
  {id: 'Biology-Y12-M6-L8', data: lesson37Data as LessonData},
  {id: 'Biology-Y12-M6-L9', data: lesson38Data as LessonData},
  {id: 'Biology-Y12-M7-L1', data: lesson39Data as LessonData},
  {id: 'Biology-Y12-M7-L10', data: lesson40Data as LessonData},
  {id: 'Biology-Y12-M7-L11', data: lesson41Data as LessonData},
  {id: 'Biology-Y12-M7-L12', data: lesson42Data as LessonData},
  {id: 'Biology-Y12-M7-L13', data: lesson43Data as LessonData},
  {id: 'Biology-Y12-M7-L14', data: lesson44Data as LessonData},
  {id: 'Biology-Y12-M7-L15', data: lesson45Data as LessonData},
  {id: 'Biology-Y12-M7-L16', data: lesson46Data as LessonData},
  {id: 'Biology-Y12-M7-L17', data: lesson47Data as LessonData},
  {id: 'Biology-Y12-M7-L18', data: lesson48Data as LessonData},
  {id: 'Biology-Y12-M7-L19', data: lesson49Data as LessonData},
  {id: 'Biology-Y12-M7-L2', data: lesson50Data as LessonData},
  {id: 'Biology-Y12-M7-L20', data: lesson51Data as LessonData},
  {id: 'Biology-Y12-M7-L21', data: lesson52Data as LessonData},
  {id: 'Biology-Y12-M7-L3', data: lesson53Data as LessonData},
  {id: 'Biology-Y12-M7-L4', data: lesson54Data as LessonData},
  {id: 'Biology-Y12-M7-L5', data: lesson55Data as LessonData},
  {id: 'Biology-Y12-M7-L6', data: lesson56Data as LessonData},
  {id: 'Biology-Y12-M7-L7', data: lesson57Data as LessonData},
  {id: 'Biology-Y12-M7-L8', data: lesson58Data as LessonData},
  {id: 'Biology-Y12-M7-L9', data: lesson59Data as LessonData},
  {id: 'Biology-Y12-M8-L1', data: lesson60Data as LessonData},
  {id: 'Biology-Y12-M8-L10', data: lesson61Data as LessonData},
  {id: 'Biology-Y12-M8-L11', data: lesson62Data as LessonData},
  {id: 'Biology-Y12-M8-L12', data: lesson63Data as LessonData},
  {id: 'Biology-Y12-M8-L13A', data: lesson64Data as LessonData},
  {id: 'Biology-Y12-M8-L13B', data: lesson65Data as LessonData},
  {id: 'Biology-Y12-M8-L14', data: lesson66Data as LessonData},
  {id: 'Biology-Y12-M8-L15', data: lesson67Data as LessonData},
  {id: 'Biology-Y12-M8-L16', data: lesson68Data as LessonData},
  {id: 'Biology-Y12-M8-L17A', data: lesson69Data as LessonData},
  {id: 'Biology-Y12-M8-L17B', data: lesson70Data as LessonData},
  {id: 'Biology-Y12-M8-L18A', data: lesson71Data as LessonData},
  {id: 'Biology-Y12-M8-L18B', data: lesson72Data as LessonData},
  {id: 'Biology-Y12-M8-L19A', data: lesson73Data as LessonData},
  {id: 'Biology-Y12-M8-L19B', data: lesson74Data as LessonData},
  {id: 'Biology-Y12-M8-L2', data: lesson75Data as LessonData},
  {id: 'Biology-Y12-M8-L20', data: lesson76Data as LessonData},
  {id: 'Biology-Y12-M8-L21', data: lesson77Data as LessonData},
  {id: 'Biology-Y12-M8-L3', data: lesson78Data as LessonData},
  {id: 'Biology-Y12-M8-L4', data: lesson79Data as LessonData},
  {id: 'Biology-Y12-M8-L5', data: lesson80Data as LessonData},
  {id: 'Biology-Y12-M8-L6', data: lesson81Data as LessonData},
  {id: 'Biology-Y12-M8-L7', data: lesson82Data as LessonData},
  {id: 'Biology-Y12-M8-L8', data: lesson83Data as LessonData},
  {id: 'Biology-Y12-M8-L9', data: lesson84Data as LessonData},
  {id: 'Chemistry-Y11-M1-L1', data: lesson85Data as LessonData},
  {id: 'Chemistry-Y11-M1-L10', data: lesson86Data as LessonData},
  {id: 'Chemistry-Y11-M1-L11', data: lesson87Data as LessonData},
  {id: 'Chemistry-Y11-M1-L12', data: lesson88Data as LessonData},
  {id: 'Chemistry-Y11-M1-L13', data: lesson89Data as LessonData},
  {id: 'Chemistry-Y11-M1-L14', data: lesson90Data as LessonData},
  {id: 'Chemistry-Y11-M1-L15', data: lesson91Data as LessonData},
  {id: 'Chemistry-Y11-M1-L16', data: lesson92Data as LessonData},
  {id: 'Chemistry-Y11-M1-L17', data: lesson93Data as LessonData},
  {id: 'Chemistry-Y11-M1-L18', data: lesson94Data as LessonData},
  {id: 'Chemistry-Y11-M1-L19', data: lesson95Data as LessonData},
  {id: 'Chemistry-Y11-M1-L2', data: lesson96Data as LessonData},
  {id: 'Chemistry-Y11-M1-L20', data: lesson97Data as LessonData},
  {id: 'Chemistry-Y11-M1-L3', data: lesson98Data as LessonData},
  {id: 'Chemistry-Y11-M1-L4', data: lesson99Data as LessonData},
  {id: 'Chemistry-Y11-M1-L5', data: lesson100Data as LessonData},
  {id: 'Chemistry-Y11-M1-L6', data: lesson101Data as LessonData},
  {id: 'Chemistry-Y11-M1-L7', data: lesson102Data as LessonData},
  {id: 'Chemistry-Y11-M1-L8', data: lesson103Data as LessonData},
  {id: 'Chemistry-Y11-M1-L9', data: lesson104Data as LessonData},
  {id: 'Chemistry-Y11-M2-L1', data: lesson105Data as LessonData},
  {id: 'Chemistry-Y11-M2-L10', data: lesson106Data as LessonData},
  {id: 'Chemistry-Y11-M2-L11', data: lesson107Data as LessonData},
  {id: 'Chemistry-Y11-M2-L12', data: lesson108Data as LessonData},
  {id: 'Chemistry-Y11-M2-L13', data: lesson109Data as LessonData},
  {id: 'Chemistry-Y11-M2-L14', data: lesson110Data as LessonData},
  {id: 'Chemistry-Y11-M2-L15', data: lesson111Data as LessonData},
  {id: 'Chemistry-Y11-M2-L16', data: lesson112Data as LessonData},
  {id: 'Chemistry-Y11-M2-L17', data: lesson113Data as LessonData},
  {id: 'Chemistry-Y11-M2-L18', data: lesson114Data as LessonData},
  {id: 'Chemistry-Y11-M2-L19', data: lesson115Data as LessonData},
  {id: 'Chemistry-Y11-M2-L1A', data: lesson116Data as LessonData},
  {id: 'Chemistry-Y11-M2-L1B', data: lesson117Data as LessonData},
  {id: 'Chemistry-Y11-M2-L2', data: lesson118Data as LessonData},
  {id: 'Chemistry-Y11-M2-L20', data: lesson119Data as LessonData},
  {id: 'Chemistry-Y11-M2-L3', data: lesson120Data as LessonData},
  {id: 'Chemistry-Y11-M2-L4', data: lesson121Data as LessonData},
  {id: 'Chemistry-Y11-M2-L5', data: lesson122Data as LessonData},
  {id: 'Chemistry-Y11-M2-L6', data: lesson123Data as LessonData},
  {id: 'Chemistry-Y11-M2-L7', data: lesson124Data as LessonData},
  {id: 'Chemistry-Y11-M2-L8', data: lesson125Data as LessonData},
  {id: 'Chemistry-Y11-M2-L9', data: lesson126Data as LessonData},
  {id: 'Chemistry-Y11-M3-Checkpoint1', data: lesson127Data as LessonData},
  {id: 'Chemistry-Y11-M3-Checkpoint2', data: lesson128Data as LessonData},
  {id: 'Chemistry-Y11-M3-Checkpoint3', data: lesson129Data as LessonData},
  {id: 'Chemistry-Y11-M3-L1', data: lesson130Data as LessonData},
  {id: 'Chemistry-Y11-M3-L10', data: lesson131Data as LessonData},
  {id: 'Chemistry-Y11-M3-L11', data: lesson132Data as LessonData},
  {id: 'Chemistry-Y11-M3-L12', data: lesson133Data as LessonData},
  {id: 'Chemistry-Y11-M3-L2', data: lesson134Data as LessonData},
  {id: 'Chemistry-Y11-M3-L3', data: lesson135Data as LessonData},
  {id: 'Chemistry-Y11-M3-L4', data: lesson136Data as LessonData},
  {id: 'Chemistry-Y11-M3-L5', data: lesson137Data as LessonData},
  {id: 'Chemistry-Y11-M3-L6', data: lesson138Data as LessonData},
  {id: 'Chemistry-Y11-M3-L7', data: lesson139Data as LessonData},
  {id: 'Chemistry-Y11-M3-L8', data: lesson140Data as LessonData},
  {id: 'Chemistry-Y11-M3-L9', data: lesson141Data as LessonData},
  {id: 'Chemistry-Y11-M4-Checkpoint1', data: lesson142Data as LessonData},
  {id: 'Chemistry-Y11-M4-Checkpoint2', data: lesson143Data as LessonData},
  {id: 'Chemistry-Y11-M4-Checkpoint3', data: lesson144Data as LessonData},
  {id: 'Chemistry-Y11-M4-L1', data: lesson145Data as LessonData},
  {id: 'Chemistry-Y11-M4-L10', data: lesson146Data as LessonData},
  {id: 'Chemistry-Y11-M4-L11', data: lesson147Data as LessonData},
  {id: 'Chemistry-Y11-M4-L12', data: lesson148Data as LessonData},
  {id: 'Chemistry-Y11-M4-L13', data: lesson149Data as LessonData},
  {id: 'Chemistry-Y11-M4-L2', data: lesson150Data as LessonData},
  {id: 'Chemistry-Y11-M4-L3', data: lesson151Data as LessonData},
  {id: 'Chemistry-Y11-M4-L4', data: lesson152Data as LessonData},
  {id: 'Chemistry-Y11-M4-L5', data: lesson153Data as LessonData},
  {id: 'Chemistry-Y11-M4-L6', data: lesson154Data as LessonData},
  {id: 'Chemistry-Y11-M4-L7', data: lesson155Data as LessonData},
  {id: 'Chemistry-Y11-M4-L8', data: lesson156Data as LessonData},
  {id: 'Chemistry-Y11-M4-L9', data: lesson157Data as LessonData},
  {id: 'Chemistry-Y12-M5-L1', data: lesson158Data as LessonData},
  {id: 'Chemistry-Y12-M5-L10', data: lesson159Data as LessonData},
  {id: 'Chemistry-Y12-M5-L11', data: lesson160Data as LessonData},
  {id: 'Chemistry-Y12-M5-L12', data: lesson161Data as LessonData},
  {id: 'Chemistry-Y12-M5-L13', data: lesson162Data as LessonData},
  {id: 'Chemistry-Y12-M5-L14', data: lesson163Data as LessonData},
  {id: 'Chemistry-Y12-M5-L15', data: lesson164Data as LessonData},
  {id: 'Chemistry-Y12-M5-L16', data: lesson165Data as LessonData},
  {id: 'Chemistry-Y12-M5-L17', data: lesson166Data as LessonData},
  {id: 'Chemistry-Y12-M5-L18', data: lesson167Data as LessonData},
  {id: 'Chemistry-Y12-M5-L2', data: lesson168Data as LessonData},
  {id: 'Chemistry-Y12-M5-L3', data: lesson169Data as LessonData},
  {id: 'Chemistry-Y12-M5-L4', data: lesson170Data as LessonData},
  {id: 'Chemistry-Y12-M5-L5', data: lesson171Data as LessonData},
  {id: 'Chemistry-Y12-M5-L6', data: lesson172Data as LessonData},
  {id: 'Chemistry-Y12-M5-L7', data: lesson173Data as LessonData},
  {id: 'Chemistry-Y12-M5-L8', data: lesson174Data as LessonData},
  {id: 'Chemistry-Y12-M5-L9', data: lesson175Data as LessonData},
  {id: 'Chemistry-Y12-M6-L1', data: lesson176Data as LessonData},
  {id: 'Chemistry-Y12-M6-L10', data: lesson177Data as LessonData},
  {id: 'Chemistry-Y12-M6-L11', data: lesson178Data as LessonData},
  {id: 'Chemistry-Y12-M6-L12', data: lesson179Data as LessonData},
  {id: 'Chemistry-Y12-M6-L13', data: lesson180Data as LessonData},
  {id: 'Chemistry-Y12-M6-L14', data: lesson181Data as LessonData},
  {id: 'Chemistry-Y12-M6-L15', data: lesson182Data as LessonData},
  {id: 'Chemistry-Y12-M6-L16', data: lesson183Data as LessonData},
  {id: 'Chemistry-Y12-M6-L17', data: lesson184Data as LessonData},
  {id: 'Chemistry-Y12-M6-L18', data: lesson185Data as LessonData},
  {id: 'Chemistry-Y12-M6-L19', data: lesson186Data as LessonData},
  {id: 'Chemistry-Y12-M6-L2', data: lesson187Data as LessonData},
  {id: 'Chemistry-Y12-M6-L3', data: lesson188Data as LessonData},
  {id: 'Chemistry-Y12-M6-L4', data: lesson189Data as LessonData},
  {id: 'Chemistry-Y12-M6-L5', data: lesson190Data as LessonData},
  {id: 'Chemistry-Y12-M6-L6', data: lesson191Data as LessonData},
  {id: 'Chemistry-Y12-M6-L7', data: lesson192Data as LessonData},
  {id: 'Chemistry-Y12-M6-L8', data: lesson193Data as LessonData},
  {id: 'Chemistry-Y12-M6-L9', data: lesson194Data as LessonData},
  {id: 'Chemistry-Y12-M7-L1', data: lesson195Data as LessonData},
  {id: 'Chemistry-Y12-M7-L10', data: lesson196Data as LessonData},
  {id: 'Chemistry-Y12-M7-L11', data: lesson197Data as LessonData},
  {id: 'Chemistry-Y12-M7-L12', data: lesson198Data as LessonData},
  {id: 'Chemistry-Y12-M7-L13', data: lesson199Data as LessonData},
  {id: 'Chemistry-Y12-M7-L14', data: lesson200Data as LessonData},
  {id: 'Chemistry-Y12-M7-L15', data: lesson201Data as LessonData},
  {id: 'Chemistry-Y12-M7-L16', data: lesson202Data as LessonData},
  {id: 'Chemistry-Y12-M7-L17', data: lesson203Data as LessonData},
  {id: 'Chemistry-Y12-M7-L18', data: lesson204Data as LessonData},
  {id: 'Chemistry-Y12-M7-L19', data: lesson205Data as LessonData},
  {id: 'Chemistry-Y12-M7-L2', data: lesson206Data as LessonData},
  {id: 'Chemistry-Y12-M7-L20', data: lesson207Data as LessonData},
  {id: 'Chemistry-Y12-M7-L21', data: lesson208Data as LessonData},
  {id: 'Chemistry-Y12-M7-L22', data: lesson209Data as LessonData},
  {id: 'Chemistry-Y12-M7-L23', data: lesson210Data as LessonData},
  {id: 'Chemistry-Y12-M7-L3', data: lesson211Data as LessonData},
  {id: 'Chemistry-Y12-M7-L4', data: lesson212Data as LessonData},
  {id: 'Chemistry-Y12-M7-L5', data: lesson213Data as LessonData},
  {id: 'Chemistry-Y12-M7-L6', data: lesson214Data as LessonData},
  {id: 'Chemistry-Y12-M7-L7', data: lesson215Data as LessonData},
  {id: 'Chemistry-Y12-M7-L8', data: lesson216Data as LessonData},
  {id: 'Chemistry-Y12-M7-L9', data: lesson217Data as LessonData},
  {id: 'Chemistry-Y12-M8-L1', data: lesson218Data as LessonData},
  {id: 'Chemistry-Y12-M8-L10', data: lesson219Data as LessonData},
  {id: 'Chemistry-Y12-M8-L11', data: lesson220Data as LessonData},
  {id: 'Chemistry-Y12-M8-L12', data: lesson221Data as LessonData},
  {id: 'Chemistry-Y12-M8-L13', data: lesson222Data as LessonData},
  {id: 'Chemistry-Y12-M8-L14', data: lesson223Data as LessonData},
  {id: 'Chemistry-Y12-M8-L15', data: lesson224Data as LessonData},
  {id: 'Chemistry-Y12-M8-L16', data: lesson225Data as LessonData},
  {id: 'Chemistry-Y12-M8-L2', data: lesson226Data as LessonData},
  {id: 'Chemistry-Y12-M8-L3', data: lesson227Data as LessonData},
  {id: 'Chemistry-Y12-M8-L4', data: lesson228Data as LessonData},
  {id: 'Chemistry-Y12-M8-L5', data: lesson229Data as LessonData},
  {id: 'Chemistry-Y12-M8-L6', data: lesson230Data as LessonData},
  {id: 'Chemistry-Y12-M8-L7', data: lesson231Data as LessonData},
  {id: 'Chemistry-Y12-M8-L8', data: lesson232Data as LessonData},
  {id: 'Chemistry-Y12-M8-L9', data: lesson233Data as LessonData},
];
