// Auto-generated by scripts/generate-lesson-registry.mjs. Do not edit by hand.
import type {LessonData} from '../lesson/types';
import lesson1Data from './chemistry-y11-m2-l1-mole-concept.json';
import lesson2Data from './chemistry-y11-m2-l2-molar-mass.json';

export const lessons: {id: string; data: LessonData}[] = [
  {id: 'Chemistry-Y11-M2-L1', data: lesson1Data as LessonData},
  {id: 'Chemistry-Y11-M2-L2', data: lesson2Data as LessonData},
];
